In [11]:
import pandas as pd
import numpy as np

In [12]:
df_multi = pd.read_csv('1007_marketing_with_picked_group11_with_id.csv', error_bad_lines=False, usecols=['MINING_DW_SUBSCR_NO', 'Groups'])

In [13]:
df_single = pd.read_csv('0814_marketing_with_picked_group11_with_id.csv', error_bad_lines=False, usecols=['MINING_DW_SUBSCR_NO', 'Groups'])

In [14]:
df_group = df_multi.append(df_single)
df_group = df_group.reset_index(drop=True)

In [5]:
mds_multi = pd.read_csv('D:/NEW_DATA_FULL_10_6/MDS_MULTI_PTYCBU_1_4.txt', error_bad_lines=False)

b'Skipping line 6552: expected 305 fields, saw 306\n'
b'Skipping line 12111: expected 305 fields, saw 306\n'
b'Skipping line 29205: expected 305 fields, saw 306\n'
b'Skipping line 39464: expected 305 fields, saw 306\n'
b'Skipping line 48445: expected 305 fields, saw 306\n'
b'Skipping line 54750: expected 305 fields, saw 306\n'
b'Skipping line 61406: expected 305 fields, saw 306\n'
b'Skipping line 69224: expected 305 fields, saw 306\n'
b'Skipping line 79784: expected 305 fields, saw 306\n'
b'Skipping line 95212: expected 305 fields, saw 306\n'
b'Skipping line 97465: expected 305 fields, saw 306\n'
b'Skipping line 151302: expected 305 fields, saw 306\n'
b'Skipping line 156252: expected 305 fields, saw 306\nSkipping line 156916: expected 305 fields, saw 306\n'
b'Skipping line 163072: expected 305 fields, saw 306\n'
b'Skipping line 174629: expected 305 fields, saw 306\n'
b'Skipping line 196450: expected 305 fields, saw 306\n'
b'Skipping line 266731: expected 305 fields, saw 306\n'
b'Skipping line 337121: expected 305 fields, saw 306\n'
b'Skipping line 375522: expected 305 fields, saw 306\n'
b'Skipping line 401174: expected 305 fields, saw 306\n'
b'Skipping line 431338: expected 305 fields, saw 306\n'
b'Skipping line 434697: expected 305 fields, saw 306\n'
b'Skipping line 449163: expected 305 fields, saw 306\n'
b'Skipping line 481748: expected 305 fields, saw 306\n'
b'Skipping line 495960: expected 305 fields, saw 306\n'
b'Skipping line 501973: expected 305 fields, saw 306\n'
b'Skipping line 508715: expected 305 fields, saw 306\n'
b'Skipping line 535966: expected 305 fields, saw 306\n'
b'Skipping line 544639: expected 305 fields, saw 306\n'
b'Skipping line 553159: expected 305 fields, saw 306\n'
b'Skipping line 573734: expected 305 fields, saw 306\n'
b'Skipping line 594194: expected 305 fields, saw 306\n'
b'Skipping line 597674: expected 305 fields, saw 306\n'
b'Skipping line 611578: expected 305 fields, saw 306\n'
b'Skipping line 626637: expected 305 fields, saw 306\n'
b'Skipping line 634341: expected 305 fields, saw 306\n'
b'Skipping line 635445: expected 305 fields, saw 306\n'
b'Skipping line 667941: expected 305 fields, saw 306\n'
b'Skipping line 675197: expected 305 fields, saw 306\n'
b'Skipping line 683816: expected 305 fields, saw 306\n'
b'Skipping line 699970: expected 305 fields, saw 306\n'
b'Skipping line 707678: expected 305 fields, saw 306\n'
b'Skipping line 805350: expected 305 fields, saw 306\n'
b'Skipping line 807782: expected 305 fields, saw 306\n'
b'Skipping line 825589: expected 305 fields, saw 306\n'
b'Skipping line 851573: expected 305 fields, saw 306\n'
b'Skipping line 857718: expected 305 fields, saw 306\n'
b'Skipping line 882519: expected 305 fields, saw 306\n'
b'Skipping line 893026: expected 305 fields, saw 306\n'
b'Skipping line 895748: expected 305 fields, saw 306\n'
b'Skipping line 910538: expected 305 fields, saw 306\n'
b'Skipping line 918387: expected 305 fields, saw 306\n'
b'Skipping line 940120: expected 305 fields, saw 306\n'
b'Skipping line 972746: expected 305 fields, saw 306\n'
b'Skipping line 1055439: expected 305 fields, saw 306\n'
b'Skipping line 1072751: expected 305 fields, saw 306\n'
b'Skipping line 1124480: expected 305 fields, saw 306\n'
b'Skipping line 1152943: expected 305 fields, saw 306\n'
b'Skipping line 1157450: expected 305 fields, saw 306\n'
b'Skipping line 1164915: expected 305 fields, saw 306\n'
b'Skipping line 1171625: expected 305 fields, saw 306\nSkipping line 1172561: expected 305 fields, saw 306\n'
b'Skipping line 1183317: expected 305 fields, saw 306\n'
b'Skipping line 1205452: expected 305 fields, saw 306\n'
b'Skipping line 1304076: expected 305 fields, saw 306\n'
b'Skipping line 1310910: expected 305 fields, saw 306\n'
b'Skipping line 1316543: expected 305 fields, saw 306\n'
b'Skipping line 1318573: expected 305 fields, saw 306\n'
b'Skipping line 1360433: expected 305 fields, saw 306\n'
b'Skipping line 1380852: expected 305 fields, saw 306\n'
b'Skipping line 1392232: expected 305 fields, saw 306\n'
b'Skipping line 1418468: expected 305 fields, saw 306\nSkipping line 1418545: expected 305 fields, saw 306\n'
b'Skipping line 1428509: expected 305 fields, saw 306\n'
b'Skipping line 1435425: expected 305 fields, saw 306\nSkipping line 1435547: expected 305 fields, saw 306\n'
b'Skipping line 1441377: expected 305 fields, saw 306\n'
b'Skipping line 1445013: expected 305 fields, saw 306\n'
b'Skipping line 1459235: expected 305 fields, saw 306\n'
b'Skipping line 1460435: expected 305 fields, saw 306\n'
b'Skipping line 1488535: expected 305 fields, saw 306\n'
b'Skipping line 1490980: expected 305 fields, saw 306\n'
b'Skipping line 1503260: expected 305 fields, saw 306\n'
b'Skipping line 1510698: expected 305 fields, saw 306\n'
b'Skipping line 1525377: expected 305 fields, saw 306\n'
b'Skipping line 1532212: expected 305 fields, saw 306\n'
b'Skipping line 1545954: expected 305 fields, saw 306\n'
b'Skipping line 1563952: expected 305 fields, saw 306\n'
b'Skipping line 1566003: expected 305 fields, saw 306\n'
b'Skipping line 1570035: expected 305 fields, saw 306\n'
b'Skipping line 1579990: expected 305 fields, saw 306\n'
b'Skipping line 1606827: expected 305 fields, saw 306\n'
b'Skipping line 1633408: expected 305 fields, saw 306\n'
b'Skipping line 1635904: expected 305 fields, saw 306\n'
b'Skipping line 1662800: expected 305 fields, saw 306\n'
b'Skipping line 1681396: expected 305 fields, saw 306\n'
b'Skipping line 1682251: expected 305 fields, saw 306\n'
b'Skipping line 1687540: expected 305 fields, saw 306\n'
b'Skipping line 1690168: expected 305 fields, saw 306\n'
b'Skipping line 1701800: expected 305 fields, saw 306\n'
b'Skipping line 1705148: expected 305 fields, saw 306\n'
b'Skipping line 1710246: expected 305 fields, saw 306\n'
b'Skipping line 1748655: expected 305 fields, saw 306\n'
b'Skipping line 1753343: expected 305 fields, saw 306\nSkipping line 1753718: expected 305 fields, saw 306\n'
b'Skipping line 1758725: expected 305 fields, saw 306\n'
b'Skipping line 1800881: expected 305 fields, saw 306\n'
b'Skipping line 1805053: expected 305 fields, saw 306\n'
b'Skipping line 1833571: expected 305 fields, saw 306\n'
b'Skipping line 1858243: expected 305 fields, saw 306\n'
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (28,198,199,200,201,214,215,227,237) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
len(mds_multi)

1889749

In [7]:
len(df_multi)

1016227

In [8]:
mds_multi = pd.merge(mds_multi, df_multi, on='MINING_DW_SUBSCR_NO', how='right')

In [9]:
len(mds_multi)

1016227

In [ ]:
mds_single = pd.read_csv('D:/20170728_single_sims_filter.csv', error_bad_lines=False)

In [ ]:
mds_full = pd.read_csv('D:/NEW_DATA_FULL_2017_6_16/MDS_ACTIVE_MLY_COMPLETED.txt', error_bad_lines=False)

In [ ]:
len(mds_full)

In [ ]:
list(mds_multi.columns)

In [ ]:
len(mds_multi.columns)

In [ ]:
len(mds_full.columns)

In [ ]:
del mds_full

In [10]:
mds_multi.to_csv('D:/multi_mds_with_group.csv', index=False, encoding='utf8')

In [16]:
df_roam = pd.read_csv('D:/NEW_DATA_FULL_2017_8_14/mds_BILL_AVG_APR.txt', error_bad_lines=False)

In [20]:
df_roam

,DATA_MONTH,MINING_DW_SUBSCR_NO,L3M_AVG_IDD_AMT,L3M_AVG_INT_ROAM_AMT,L3M_AVG_GPRS_AMT,L3M_AVG_OFFNET_AMT,L3M_AVG_ONNET_AMT,L3M_AVG_PSTN_AMT
0,2017/4/1,3133106244,0,0,0,0,0,0
1,2017/4/1,2118544651,0,0,0,0,0,3
2,2017/4/1,10000337216,0,0,0,0,0,13
3,2017/4/1,3137418985,0,0,0,254,124,148
4,2017/4/1,3119268553,0,13,0,0,0,0
5,2017/4/1,3127411643,0,0,0,0,239,0
6,2017/4/1,3134824681,0,0,0,0,0,55
7,2017/4/1,8131713026,0,0,0,0,0,46
8,2017/4/1,3128848146,0,0,0,0,0,7
9,2017/4/1,8131875978,0,0,0,0,0,0
10,2017/4/1,3129112943,0,0,0,2,1,0
11,2017/4/1,3124837708,0,0,485,0,0,12
12,2017/4/1,3136906528,0,0,0,3,1,0
13,2017/4/1,3136438041,0,0,0,0,0,0
14,2017/4/1,3123476217,0,0,0,0,0,88
15,2017/4/1,8136932676,0,0,0,0,0,21
16,2017/4/1,10001380244,0,0,0,0,0,0
17,2017/4/1,3128800944,0,0,0,0,0,29
18,2017/4/1,3116365482,0,0,0,0,0,106
19,2017/4/1,8136912307,0,0,0,0,0,136
20,2017/4/1,3116484464,0,0,0,0,0,7
21,2017/4/1,3114599843,0,0,0,0,0,47
22,2017/4/1,3123106343,0,0,0,190,3,50
23,2017/4/1,8134330931,0,0,0,0,10,0
24,2017/4/1,3119251416,0,0,0,0,0,85
25,2017/4/1,3125975140,0,0,0,7,0,145
26,2017/4/1,8136334534,0,0,0,0,0,0
27,2017/4/1,5128482132,0,0,0,32,0,4
28,2017/4/1,3121112436,0,0,0,0,0,0
29,2017/4/1,3125061767,0,0,0,0,0,36
...,...,...,...,...,...,...,...,...
6066194,2017/4/1,3114192463,1,0,0,1,0,6
6066195,2017/4/1,3128573653,0,0,0,0,0,23
6066196,2017/4/1,3131857271,0,0,0,0,0,0
6066197,2017/4/1,3118630650,0,0,0,73,0,11
6066198,2017/4/1,8131927389,0,0,0,0,0,0
6066199,2017/4/1,1113227051,0,0,0,0,0,0
6066200,2017/4/1,2113933816,0,0,0,0,0,5
6066201,2017/4/1,3118104288,0,0,0,0,0,103
6066202,2017/4/1,3132118836,0,0,0,0,0,0
6066203,2017/4/1,8131034385,0,0,0,0,0,9
6066204,2017/4/1,1110024909,0,0,0,0,0,2
6066205,2017/4/1,8135652661,0,0,0,0,3,1
6066206,2017/4/1,10000181705,41,0,0,0,0,10
6066207,2017/4/1,10001336274,0,0,0,0,0,0
6066208,2017/4/1,3129283336,0,0,0,0,0,0
6066209,2017/4/1,3130437905,0,0,0,0,0,0
6066210,2017/4/1,2117659088,0,0,0,0,4,158
6066211,2017/4/1,3131592474,0,0,0,0,0,0
6066212,2017/4/1,8133971730,0,0,0,0,0,37
6066213,2017/4/1,3137365319,0,0,0,145,1,31
6066214,2017/4/1,10000809912,0,0,0,0,0,4
6066215,2017/4/1,3129911543,0,0,0,0,0,12
6066216,2017/4/1,111080551,0,0,0,0,0,0
6066217,2017/4/1,8133951361,0,0,0,9,1,1
6066218,2017/4/1,3120331950,0,0,0,0,0,17
6066219,2017/4/1,3124950226,0,0,0,0,0,0
6066220,2017/4/1,3126104795,0,0,0,0,0,0
6066221,2017/4/1,2114480547,0,0,0,0,0,4
6066222,2017/4/1,3128413933,0,0,0,2,11,121
6066223,2017/4/1,3115187312,2,0,0,0,59,21

In [22]:
df_roam = df_roam[['MINING_DW_SUBSCR_NO', 'L3M_AVG_INT_ROAM_AMT']]
df_roam = pd.merge(df_roam, df_group, how='right', on='MINING_DW_SUBSCR_NO')
df_roam

,MINING_DW_SUBSCR_NO,L3M_AVG_INT_ROAM_AMT,Groups
0,2118544651,0.0,No_significant_preference
1,10000337216,0.0,No_significant_preference
2,3134824681,0.0,No_significant_preference(instant_message)
3,8131713026,0.0,InstantMessage-High
4,3128848146,0.0,No_significant_preference
5,8131875978,0.0,Infrequent_User
6,3129112943,0.0,No_significant_preference(instant_message)
7,3136906528,0.0,No_significant_preference
8,3136438041,0.0,Infrequent_User
9,3123476217,0.0,No_significant_preference(instant_message)
10,8136932676,0.0,No_significant_preference
11,3128800944,0.0,No_significant_preference(instant_message)
12,3116365482,0.0,Social-media
13,8136912307,0.0,No_significant_preference
14,3116484464,0.0,Adult
15,3114599843,0.0,No_significant_preference
16,3123106343,0.0,No_significant_preference
17,3119251416,0.0,Lifestyle
18,3125975140,0.0,Social-media
19,8136334534,0.0,Game
20,3125061767,0.0,InstantMessage-High
21,3117930663,0.0,InstantMessage-SuperHigh
22,8133030547,0.0,InstantMessage-SuperHigh
23,10000354353,0.0,No_significant_preference(instant_message)
24,8135822077,0.0,Adult
25,8135353590,0.0,No_significant_preference(instant_message)
26,8135618387,0.0,No_significant_preference(instant_message)
27,3116728892,0.0,Game
28,3130746672,0.0,InstantMessage-High
29,3128981033,0.0,No_significant_preference
...,...,...,...
2828142,3116861779,0.0,No_significant_preference
2828143,8132467656,0.0,Infrequent_User
2828144,3122634624,0.0,InstantMessage-High
2828145,3137015814,0.0,No_significant_preference
2828146,8135931363,4.0,InstantMessage-SuperHigh
2828147,10000460407,0.0,No_significant_preference(instant_message)
2828148,3127252900,0.0,InstantMessage-SuperHigh
2828149,8134980484,0.0,Adult
2828150,3127456590,0.0,Lifestyle
2828151,3132074866,0.0,Social-media
2828152,10000949263,0.0,No_significant_preference(instant_message)
2828153,2113808370,0.0,Game
2828154,3127741756,0.0,Entertainment
2828155,119322254,0.0,No_significant_preference
2828156,8131275581,0.0,No_significant_preference
2828157,3121442549,0.0,No_significant_preference
2828158,8134942978,0.0,InstantMessage-High
2828159,3114192463,0.0,InstantMessage-High
2828160,3128573653,0.0,No_significant_preference
2828161,3118630650,0.0,No_significant_preference
2828162,1110024909,0.0,No_significant_preference
2828163,8135652661,0.0,Entertainment
2828164,3131592474,0.0,Game
2828165,3129911543,0.0,Entertainment
2828166,8133951361,0.0,No_significant_preference
2828167,3120331950,0.0,Game
2828168,3124950226,0.0,No_significant_preference
2828169,3126104795,0.0,No_significant_preference(instant_message)
2828170,2115579859,NaN,No_significant_preference
2828171,2116577982,NaN,No_significant_preference

In [24]:
df_roam[df_roam.L3M_AVG_INT_ROAM_AMT != 0].count()

MINING_DW_SUBSCR_NO     109855
L3M_AVG_INT_ROAM_AMT    109853
Groups                  109855
dtype: int64

In [29]:
df_roam[df_roam.L3M_AVG_INT_ROAM_AMT != 0].groupby('Groups').L3M_AVG_INT_ROAM_AMT.mean()

Groups
Adult                                         155.731771
Entertainment                                 179.839299
Game                                          177.165110
Infrequent_User                               121.059755
InstantMessage-High                           202.408686
InstantMessage-SuperHigh                      233.152333
Lifestyle                                     184.879566
No_significant_preference                     156.707073
No_significant_preference(instant_message)    177.433852
Portal                                        136.570761
Social-media                                  164.053203
Name: L3M_AVG_INT_ROAM_AMT, dtype: float64

In [28]:
df_roam.Groups.value_counts()

InstantMessage-High                           524773
No_significant_preference                     496388
InstantMessage-SuperHigh                      478936
No_significant_preference(instant_message)    416587
Infrequent_User                               187638
Social-media                                  186118
Portal                                        146720
Game                                          131366
Lifestyle                                     111266
Adult                                          78781
Entertainment                                  69599
Name: Groups, dtype: int64