In [55]:
import os.path
import numpy as np
import pandas as pd
from time import time

In [56]:
# set configure
# path = "../DATA_FULL/"
path = "D:/NEW_DATA_FULL_2017_6_14/"
filename = "CDR_USAGE_MO_HOUR_COMPLETED"
Date_col = "VOICE_DATE"
# relative_filename = path + filename + ".csv"
select_month = 4
relative_filename = path + filename + ".txt"
out_filename = filename + "_" + str(select_month) + "_revise"
# after the numeric_st_idx's number will be tranform to int64
numeric_st_idx = 2
chunk_count = 0
# pick the columns of u wants
# wants_cols = ['DATA_MONTH', 'MINING_DW_SUBSCR_NO', 'AGE', "MO_TTL_DURATION","MO_ONNET_DUR","MO_OFFNET_DUR","PSTN_DUR","MO_TTL_COUNT","MO_ONNET_CNT","MO_OFFNET_CNT","PSTN_CNT","MT_TTL_DURATION","MT_ONNET_DUR","MT_OFFNET_DUR","MT_PSTN_DUR","MT_TTL_COUNT","MT_ONNET_CNT","MT_OFFNET_CNT","MT_PSTN_CNT","MOC_FET_DUR","MOC_TWM_DUR","MOC_CHM_DUR","MOC_OTH_DUR","MOC_PSTN_DUR","MOST_MO_DUR","MTC_FMT_DUR"]

In [57]:
# read csv file and print cost time
t0 = time()
# df = pd.read_csv(relative_filename, usecols = wants_cols, error_bad_lines=False)
# df = pd.read_csv(relative_filename, error_bad_lines=False, nrows=100)
df = pd.read_csv(relative_filename, error_bad_lines=False, nrows=100)
print("time for read csv: %.2f" % (time()-t0))
# df.head()

time for read csv: 0.05

In [58]:
select_month_df =  pd.DataFrame()

In [59]:
chunks=pd.read_table(relative_filename ,chunksize=2**21,sep=',',\
		parse_dates=[Date_col],\
        error_bad_lines=False)

In [60]:
t0 = time()

for chunk in chunks:
    
#     df[Date_col] = pd.to_datetime(df[Date_col])
#     select_month_partition = df[df[Date_col].dt.month == select_month]
    chunk[Date_col] = pd.to_datetime(chunk[Date_col])
    select_month_partition = chunk[chunk[Date_col].dt.month == select_month]
    select_month_df = select_month_df.append(select_month_partition, ignore_index=True)
    chunk_count+=1
    print(chunk_count)
print("time for select month csv: %.2f" % (time()-t0))

C:\Users\VIPLAB\AppData\Local\conda\conda\envs\py36\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
time for select month csv: 1951.44

In [61]:
def save_dataframe(df, out_filename):
   # write to csv and no index
    t0 = time()
    df.to_csv(out_filename + ".csv", index=False, encoding='utf-8')
    print("time for output csv file: %.2f" % (time()-t0))

In [62]:
save_dataframe(select_month_df, out_filename)

time for output csv file: 1554.02

In [46]:
select_month_df.head()

,MINING_DW_SUBSCR_NO,VOICE_DATE,VOICE_MT_HOUR_0_CNT,VOICE_MT_HOUR_1_CNT,VOICE_MT_HOUR_2_CNT,VOICE_MT_HOUR_3_CNT,VOICE_MT_HOUR_4_CNT,VOICE_MT_HOUR_5_CNT,VOICE_MT_HOUR_6_CNT,VOICE_MT_HOUR_7_CNT,...,VOICE_MT_HOUR_14_TIME,VOICE_MT_HOUR_15_TIME,VOICE_MT_HOUR_16_TIME,VOICE_MT_HOUR_17_TIME,VOICE_MT_HOUR_18_TIME,VOICE_MT_HOUR_19_TIME,VOICE_MT_HOUR_20_TIME,VOICE_MT_HOUR_21_TIME,VOICE_MT_HOUR_22_TIME,VOICE_MT_HOUR_23_TIME
0,10001140668,2017-04-01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,36,0,0,0
1,10000769025,2017-04-02,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,850,0,0,0
2,10001140668,2017-04-02,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
3,10000769025,2017-04-03,1,0,0,0,0,0,0,0,...,0,0,0,0,0,56,0,0,0,0
4,10001140668,2017-04-03,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,124,0

In [ ]:
# slice 12months data
for month_idx in range(1,13):
    divide_month = df[df['VOICE_MONTH'].dt.month == month_idx]
    if(len(divide_month) == 0):
        continue
    # write to csv and no index
    t0 = time()
    divide_month.to_csv(out_filename + str(month_idx) + ".csv", index=False)
    print("time for output csv file: %.2f" % (time()-t0))

In [ ]:
del df