In [179]:
# coding: utf-8
import pandas as pd
import numpy as np
import plotly.offline as py
import plotly.graph_objs as go
import sys

In [180]:
# py.offline.init_notebook_mode()
output_path = "./CDR_CONCAT_ANALYZE_GRAPH/"

# path = "./CDR_ANALYZE/"
path = "C:/Users/VIPLAB/Desktop/XIAO SEAN/"
filename = "DNA_VOICE_revise.csv"
# opt = "VOICE"
opt = "DNA"

# filename = sys.argv[1]

In [181]:
df_src = pd.read_csv(path + filename, error_bad_lines = False)

In [182]:
df_src.head()

,VOICE_HOUR_0_TIME,VOICE_HOUR_1_TIME,VOICE_HOUR_2_TIME,VOICE_HOUR_3_TIME,VOICE_HOUR_4_TIME,VOICE_HOUR_5_TIME,VOICE_HOUR_6_TIME,VOICE_HOUR_7_TIME,VOICE_HOUR_8_TIME,VOICE_HOUR_9_TIME,...,DNA_HOUR_15_COUNT,DNA_HOUR_16_COUNT,DNA_HOUR_17_COUNT,DNA_HOUR_18_COUNT,DNA_HOUR_19_COUNT,DNA_HOUR_20_COUNT,DNA_HOUR_21_COUNT,DNA_HOUR_22_COUNT,DNA_HOUR_23_COUNT,groups
0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.005,0.001,0.030,...,0.028,0.100,0.062,0.035,0.039,0.035,0.037,0.053,0.037,3
1,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.605,0.026,0.000,0.000,0.000,0.000,0.000,15
2,0.0,0.0,0.0,0.0,0.0,0.003,0.007,0.001,0.018,0.111,...,0.033,0.069,0.049,0.101,0.056,0.102,0.094,0.128,0.084,3
3,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.054,0.030,0.004,0.010,0.012,0.048,0.074,0.000,0.036,13
4,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2

In [183]:
groups_name = [i for i in range(1, 18)]
# groups_name = ['1', '2', '3', '4', '5', '6', '7', '8', 'seldom', 'None']
# groups_name = ['1', '2', '3', '4', '5', '6', '7', '8']

Ks = [6, 5, 5, 5, 5, 5, 5, 5]
# Ks = [8, 7, 6, 7, 5, 6, 6, 8, 7, 7]


date = "0706_v1"
# df_src['Groups'] = df_group['Groups']

# for K in range(7, 10):
# 	for group in groups_name:
# group = groups_name[i]
group = "Groups"

# df = df_src[df_src['groups'] == group]
# group = filename[15:-4]

In [184]:
# wants_cols = [x for x in  df_src.columns if "DNA" ]
wants_cols = [x for x in  df_src.columns if opt in x ]

In [185]:
df = df_src[wants_cols]

In [186]:
df.head()

,DNA_HOUR_0_COUNT,DNA_HOUR_1_COUNT,DNA_HOUR_2_COUNT,DNA_HOUR_3_COUNT,DNA_HOUR_4_COUNT,DNA_HOUR_5_COUNT,DNA_HOUR_6_COUNT,DNA_HOUR_7_COUNT,DNA_HOUR_8_COUNT,DNA_HOUR_9_COUNT,...,DNA_HOUR_14_COUNT,DNA_HOUR_15_COUNT,DNA_HOUR_16_COUNT,DNA_HOUR_17_COUNT,DNA_HOUR_18_COUNT,DNA_HOUR_19_COUNT,DNA_HOUR_20_COUNT,DNA_HOUR_21_COUNT,DNA_HOUR_22_COUNT,DNA_HOUR_23_COUNT
0,0.020,0.003,0.002,0.003,0.014,0.012,0.014,0.088,0.095,0.061,...,0.029,0.028,0.100,0.062,0.035,0.039,0.035,0.037,0.053,0.037
1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.605,0.026,0.000,0.000,0.000,0.000,0.000
2,0.032,0.009,0.002,0.000,0.004,0.000,0.023,0.022,0.014,0.019,...,0.023,0.033,0.069,0.049,0.101,0.056,0.102,0.094,0.128,0.084
3,0.211,0.038,0.000,0.000,0.000,0.000,0.008,0.006,0.008,0.004,...,0.046,0.054,0.030,0.004,0.010,0.012,0.048,0.074,0.000,0.036
4,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [187]:
sum(df.loc[2])

0.999

In [189]:
df.loc[0]

DNA_HOUR_0_COUNT     0.020
DNA_HOUR_1_COUNT     0.003
DNA_HOUR_2_COUNT     0.002
DNA_HOUR_3_COUNT     0.003
DNA_HOUR_4_COUNT     0.014
DNA_HOUR_5_COUNT     0.012
DNA_HOUR_6_COUNT     0.014
DNA_HOUR_7_COUNT     0.088
DNA_HOUR_8_COUNT     0.095
DNA_HOUR_9_COUNT     0.061
DNA_HOUR_10_COUNT    0.060
DNA_HOUR_11_COUNT    0.041
DNA_HOUR_12_COUNT    0.048
DNA_HOUR_13_COUNT    0.085
DNA_HOUR_14_COUNT    0.029
DNA_HOUR_15_COUNT    0.028
DNA_HOUR_16_COUNT    0.100
DNA_HOUR_17_COUNT    0.062
DNA_HOUR_18_COUNT    0.035
DNA_HOUR_19_COUNT    0.039
DNA_HOUR_20_COUNT    0.035
DNA_HOUR_21_COUNT    0.037
DNA_HOUR_22_COUNT    0.053
DNA_HOUR_23_COUNT    0.037
Name: 0, dtype: float64

In [190]:
wants_cols.append("groups")
wants_cols

['DNA_HOUR_0_COUNT',
 'DNA_HOUR_1_COUNT',
 'DNA_HOUR_2_COUNT',
 'DNA_HOUR_3_COUNT',
 'DNA_HOUR_4_COUNT',
 'DNA_HOUR_5_COUNT',
 'DNA_HOUR_6_COUNT',
 'DNA_HOUR_7_COUNT',
 'DNA_HOUR_8_COUNT',
 'DNA_HOUR_9_COUNT',
 'DNA_HOUR_10_COUNT',
 'DNA_HOUR_11_COUNT',
 'DNA_HOUR_12_COUNT',
 'DNA_HOUR_13_COUNT',
 'DNA_HOUR_14_COUNT',
 'DNA_HOUR_15_COUNT',
 'DNA_HOUR_16_COUNT',
 'DNA_HOUR_17_COUNT',
 'DNA_HOUR_18_COUNT',
 'DNA_HOUR_19_COUNT',
 'DNA_HOUR_20_COUNT',
 'DNA_HOUR_21_COUNT',
 'DNA_HOUR_22_COUNT',
 'DNA_HOUR_23_COUNT',
 'groups']

In [191]:
df = df_src[wants_cols]

In [192]:
# df.loc['label',list(map(str, df.index))] = labels_
print(group)

Groups

In [193]:
df.head()

,DNA_HOUR_0_COUNT,DNA_HOUR_1_COUNT,DNA_HOUR_2_COUNT,DNA_HOUR_3_COUNT,DNA_HOUR_4_COUNT,DNA_HOUR_5_COUNT,DNA_HOUR_6_COUNT,DNA_HOUR_7_COUNT,DNA_HOUR_8_COUNT,DNA_HOUR_9_COUNT,...,DNA_HOUR_15_COUNT,DNA_HOUR_16_COUNT,DNA_HOUR_17_COUNT,DNA_HOUR_18_COUNT,DNA_HOUR_19_COUNT,DNA_HOUR_20_COUNT,DNA_HOUR_21_COUNT,DNA_HOUR_22_COUNT,DNA_HOUR_23_COUNT,groups
0,0.020,0.003,0.002,0.003,0.014,0.012,0.014,0.088,0.095,0.061,...,0.028,0.100,0.062,0.035,0.039,0.035,0.037,0.053,0.037,3
1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.605,0.026,0.000,0.000,0.000,0.000,0.000,15
2,0.032,0.009,0.002,0.000,0.004,0.000,0.023,0.022,0.014,0.019,...,0.033,0.069,0.049,0.101,0.056,0.102,0.094,0.128,0.084,3
3,0.211,0.038,0.000,0.000,0.000,0.000,0.008,0.006,0.008,0.004,...,0.054,0.030,0.004,0.010,0.012,0.048,0.074,0.000,0.036,13
4,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2

In [194]:
grouped = df.groupby('groups')

# df['label'] = labels_
# grouped = df.drop(['MINING_DW_SUBSCR_NO'], 1).groupby('groups')
# grouped = df.groupby('label')

In [195]:
# get count
group_count = grouped[df.columns[1]].count().values
# df = df.drop('MINING_DW_SUBSCR_NO', 1)

In [196]:
group_mean

,DNA_HOUR_0_COUNT,DNA_HOUR_1_COUNT,DNA_HOUR_2_COUNT,DNA_HOUR_3_COUNT,DNA_HOUR_4_COUNT,DNA_HOUR_5_COUNT,DNA_HOUR_6_COUNT,DNA_HOUR_7_COUNT,DNA_HOUR_8_COUNT,DNA_HOUR_9_COUNT,...,DNA_HOUR_14_COUNT,DNA_HOUR_15_COUNT,DNA_HOUR_16_COUNT,DNA_HOUR_17_COUNT,DNA_HOUR_18_COUNT,DNA_HOUR_19_COUNT,DNA_HOUR_20_COUNT,DNA_HOUR_21_COUNT,DNA_HOUR_22_COUNT,DNA_HOUR_23_COUNT
groups,,,,,,,,,,,,,,,,,,,,,
1,0.006354,0.003716,0.002420,0.001653,0.001584,0.002191,0.005453,0.013421,0.014232,0.016107,...,0.020345,0.020005,0.019065,0.021422,0.019659,0.017536,0.015420,0.013044,0.009982,0.006936
2,0.004030,0.002767,0.002013,0.001630,0.001412,0.001587,0.002493,0.003430,0.004058,0.004281,...,0.004823,0.004901,0.004869,0.005200,0.005364,0.005622,0.005747,0.005489,0.004792,0.003823
3,0.019627,0.013404,0.008946,0.006325,0.005062,0.005549,0.009869,0.016082,0.020079,0.022341,...,0.028096,0.028651,0.028447,0.029652,0.030223,0.030132,0.029038,0.026960,0.023745,0.019380
4,0.014065,0.010042,0.007093,0.005096,0.004291,0.004680,0.007722,0.012378,0.015617,0.017897,...,0.023158,0.024830,0.022991,0.023288,0.022768,0.022239,0.021461,0.019199,0.016534,0.013403
5,0.011116,0.007285,0.005209,0.004276,0.004147,0.005255,0.009474,0.015513,0.019218,0.021695,...,0.019308,0.019338,0.019311,0.019958,0.019781,0.019844,0.018913,0.017651,0.014852,0.011532
6,0.000247,0.000363,0.000619,0.000832,0.000899,0.001031,0.001056,0.000456,0.000303,0.000216,...,0.000113,0.000112,0.000112,0.000116,0.000109,0.000128,0.000118,0.000130,0.000152,0.000157
7,0.017746,0.011542,0.007440,0.005095,0.004048,0.004360,0.008351,0.013760,0.015990,0.018007,...,0.022028,0.022690,0.022554,0.024881,0.025498,0.026155,0.026543,0.026661,0.022968,0.018026
8,0.011859,0.007790,0.005290,0.004134,0.003849,0.004756,0.008664,0.014120,0.017637,0.019943,...,0.020130,0.020931,0.020388,0.020602,0.020301,0.020510,0.019969,0.018351,0.015696,0.012291
9,0.013695,0.009080,0.005965,0.004316,0.003684,0.004304,0.009408,0.014976,0.015723,0.017460,...,0.021202,0.022094,0.023746,0.030512,0.026482,0.024679,0.023351,0.021401,0.018125,0.014126
10,0.014215,0.009914,0.006828,0.005026,0.004136,0.004463,0.007601,0.012363,0.015507,0.017692,...,0.022623,0.022174,0.021792,0.022295,0.022305,0.022153,0.021052,0.019209,0.016711,0.013781
11,0.014076,0.009192,0.006126,0.004315,0.003607,0.004207,0.008436,0.014404,0.016371,0.018131,...,0.021769,0.022110,0.021307,0.023795,0.023691,0.023067,0.022525,0.020607,0.018009,0.014118
12,0.006269,0.003823,0.002510,0.001997,0.001858,0.002720,0.005897,0.011662,0.018589,0.036073,...,0.020420,0.020066,0.018337,0.017182,0.016055,0.015285,0.013890,0.012122,0.009661,0.006889
13,0.013352,0.009427,0.006480,0.004723,0.004049,0.004514,0.008395,0.013101,0.015561,0.017478,...,0.022096,0.023145,0.025424,0.024653,0.023193,0.022545,0.021645,0.019848,0.017076,0.013291
14,0.006670,0.004166,0.002651,0.001903,0.001678,0.002551,0.005147,0.009825,0.014369,0.019678,...,0.021244,0.020629,0.019207,0.018667,0.017103,0.016150,0.014312,0.012528,0.009989,0.007333
15,0.015330,0.010027,0.006720,0.004990,0.004249,0.005108,0.009769,0.015235,0.016656,0.017721,...,0.020970,0.021511,0.021695,0.024649,0.026553,0.028893,0.028267,0.024958,0.020661,0.015779
16,0.014433,0.009517,0.006500,0.004661,0.003949,0.004602,0.009089,0.014739,0.016511,0.017510,...,0.021092,0.021873,0.022381,0.026111,0.029278,0.026529,0.024497,0.022151,0.018845,0.014649
17,0.012853,0.008590,0.005738,0.004311,0.003657,0.004388,0.008132,0.013376,0.016669,0.019220,...,0.020944,0.021384,0.020999,0.021799,0.021519,0.021101,0.020449,0.018536,0.015818,0.012762

In [197]:
# get mean
# group_mean = grouped.mean() / 2

In [198]:
y_list = []
for index, value in enumerate(group_count):
	y_list.append("G%d : %s" % (index, value))

In [200]:
trace = go.Heatmap(
	# x = list(map(lambda x: " " + str(x + 1), range(K))),
	# z = np.delete(group_mean.values, 0, 1),
	z = group_mean.values,
	x = df.columns[1:-1],
	# y = list(map(lambda x: "G%s " + str(x), group_count)),
	y = y_list,
	colorscale = 'Jet',
    zmin = 0,
    zmax = 0.1
)

data = [trace]

title = ("Group %s" % (group))
layout = go.Layout(title = title)

fig = go.Figure(data = data, layout = layout)
output_filename = ("%s_%s_heat_%s.html" % (filename[:-4], date, opt))
# py.plot(fig, filename = output_path + output_filename, image_height = 6000, image_width = 8000)
py.plot(fig, filename = output_path + output_filename, image_height = 6000, image_width = 8000, auto_open = False)

'file://C:\\Users\\VIPLAB\\Desktop\\preprocess_py\\CDR_CONCAT_ANALYZE_GRAPH\\DNA_VOICE_revise_0706_v1_heat_DNA.html'

In [101]:
# for i in range(8):
# 	K = Ks[i]
# 	group = groups_name[i]
# 	df = df_src[df_src['groups'] == group]
# 	# group = filename[15:-4]

# 	label_path = "./kmean_label/"
# 	label_name = "label_K" + str(K) + "_de_with_kid_" + group + "_" + date + ".npy"
# 	labels_ = np.load(label_path + label_name)

# 	# df.loc['label',list(map(str, df.index))] = labels_
# 	print(group)
# 	df['label'] = labels_
# 	grouped = df.drop(['MINING_DW_SUBSCR_NO', 'Groups'], 1).groupby('label')
# 	# grouped = df.groupby('label')

# 	# get count
# 	group_count = grouped[df.columns[1]].count().values
# 	# df = df.drop('MINING_DW_SUBSCR_NO', 1)	

# 	# get mean
# 	group_mean = grouped.mean()

# 	trace = go.Heatmap(
# 		# x = list(map(lambda x: " " + str(x + 1), range(K))),
# 		# z = np.delete(group_mean.values, 0, 1),
# 		z = group_mean.values,
# 		x = df.columns[1:-1],
# 		y = list(map(lambda x: "G " + str(x), group_count)),
# 		colorscale = 'Jet'
# 	)

# 	data = [trace]

# 	title = ("Group %s" % (group))
# 	layout = go.Layout(title = title)

# 	fig = go.Figure(data = data, layout = layout)
# 	output_filename = ("%s_K%d_G%s_%s_heat.html" % (filename[:-4], K, group, date))
# 	# py.plot(fig, filename = output_path + output_filename, image_height = 6000, image_width = 8000)
# 	py.plot(fig, filename = output_path + output_filename, image_height = 6000, image_width = 8000, auto_open = False)