In [1]:
import os.path
import numpy as np
import pandas as pd
from time import time

In [2]:
def read_csv(filename):
    # read revise csv file and print cost time
    t0 = time()
    df = pd.read_csv(filename, error_bad_lines=False)
    print("time for read csv: %.2f" % (time()-t0))
    return df

In [12]:
# set configure
# path = "./CDR_MONTHLY_AGGR/"
path = "D:/NEW_DATA_FULL_2017_7_4/"
# path = "C:/Users/VIPLAB/Downloads/Spark_data/"
# path = "./kid/"
filename1 = "MDS_SINGLESIM_APRIL_DORMANT_AGE_TENURE_COMPLETED"
relative_filename1 = path + filename1 + ".txt"

path = "./CDR_FINAL/"
filename2 = "table_with_kid_all"
# filename = "weekday_end_april_div_week"

# path = "./"
# filename = "dm_subscr_mtc_mly_COMPLETED_revise"
relative_filename2 = path + filename2 + ".csv"

# relative_filename = path + filename + ".txt"
# wants_cols = ['DATA_MONTH', 'MINING_DW_SUBSCR_NO', 'AGE', "MO_TTL_DURATION","MO_ONNET_DUR","MO_OFFNET_DUR","PSTN_DUR","MO_TTL_COUNT","MO_ONNET_CNT","MO_OFFNET_CNT","PSTN_CNT","MT_TTL_DURATION","MT_ONNET_DUR","MT_OFFNET_DUR","MT_PSTN_DUR","MT_TTL_COUNT","MT_ONNET_CNT","MT_OFFNET_CNT","MT_PSTN_CNT","MOC_FET_DUR","MOC_TWM_DUR","MOC_CHM_DUR","MOC_OTH_DUR","MOC_PSTN_DUR","MOST_MO_DUR","MTC_FET_DUR","MTC_TWM_DUR","MTC_CHM_DUR","MTC_PSTN_DUR","MOST_MT_DUR"]

In [8]:
df1 = read_csv(relative_filename1)

time for read csv: 1.18

In [18]:
df1 = df1[df1["DORMANT_MONTH_CNT_MKT"] > 0]

In [19]:
df1.head()

,DATA_MONTH,MINING_DW_SUBSCR_NO,AGE,PTY_CBU_PO_CNT,DORMANT_MONTH_CNT_MKT,TENURE_SCV
4,2017/4/1,3119268553,56,1,3,94.1
9,2017/4/1,3118052877,58,1,6,100.9
62,2017/4/1,11308457,36,1,6,195.0
77,2017/4/1,8137509472,40,1,6,9.2
82,2017/4/1,2113896310,32,1,2,145.2

In [13]:
df2 = read_csv(relative_filename2)

time for read csv: 28.18

In [14]:
df2.head()

,MINING_DW_SUBSCR_NO,Groups,VOICE_HOUR_0_TIME,VOICE_HOUR_1_TIME,VOICE_HOUR_2_TIME,VOICE_HOUR_3_TIME,VOICE_HOUR_4_TIME,VOICE_HOUR_5_TIME,VOICE_HOUR_6_TIME,VOICE_HOUR_7_TIME,...,DNA_HOUR_15_CNT,DNA_HOUR_16_CNT,DNA_HOUR_17_CNT,DNA_HOUR_18_CNT,DNA_HOUR_19_CNT,DNA_HOUR_20_CNT,DNA_HOUR_21_CNT,DNA_HOUR_22_CNT,DNA_HOUR_23_CNT,dna_monthly_sum
0,10000000005,None,0.0,0.0,0.0,0.0,0.0,0.0,0.032,0.016,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,10000000006,seldom,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,10000000008,8,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,...,0.058,0.048,0.060,0.054,0.041,0.049,0.047,0.034,0.037,0.005
3,10000000013,8,0.0,0.0,0.0,0.0,0.0,0.0,0.028,0.032,...,0.017,0.018,0.018,0.032,0.048,0.306,0.140,0.024,0.042,0.007
4,10000000020,4,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,...,0.091,0.037,0.124,0.142,0.010,0.068,0.053,0.014,0.008,0.001

In [22]:
s1 = pd.merge(df1, df2, how='inner', on=['MINING_DW_SUBSCR_NO'])

In [23]:
len(df1)

126377

In [24]:
len(s1)

126377

In [4]:
df[df["MINING_DW_SUBSCR_NO"] == 8134330931]

Empty DataFrame
Columns: [MINING_DW_SUBSCR_NO, VOICE_HOUR_0_TIME, VOICE_HOUR_1_TIME, VOICE_HOUR_2_TIME, VOICE_HOUR_3_TIME, VOICE_HOUR_4_TIME, VOICE_HOUR_5_TIME, VOICE_HOUR_6_TIME, VOICE_HOUR_7_TIME, VOICE_HOUR_8_TIME, VOICE_HOUR_9_TIME, VOICE_HOUR_10_TIME, VOICE_HOUR_11_TIME, VOICE_HOUR_12_TIME, VOICE_HOUR_13_TIME, VOICE_HOUR_14_TIME, VOICE_HOUR_15_TIME, VOICE_HOUR_16_TIME, VOICE_HOUR_17_TIME, VOICE_HOUR_18_TIME, VOICE_HOUR_19_TIME, VOICE_HOUR_20_TIME, VOICE_HOUR_21_TIME, VOICE_HOUR_22_TIME, VOICE_HOUR_23_TIME, VOICE_HOUR_MON_TIME, VOICE_HOUR_TUE_TIME, VOICE_HOUR_WED_TIME, VOICE_HOUR_THU_TIME, VOICE_HOUR_FRI_TIME, VOICE_HOUR_SAT_TIME, VOICE_HOUR_SUN_TIME, DNA_Monday, DNA_Tuesday, DNA_Wednesday, DNA_Thursday, DNA_Friday, DNA_Saturday, DNA_Sunday, DNA_HOUR_0_CNT, DNA_HOUR_1_CNT, DNA_HOUR_2_CNT, DNA_HOUR_3_CNT, DNA_HOUR_4_CNT, DNA_HOUR_5_CNT, DNA_HOUR_6_CNT, DNA_HOUR_7_CNT, DNA_HOUR_8_CNT, DNA_HOUR_9_CNT, DNA_HOUR_10_CNT, DNA_HOUR_11_CNT, DNA_HOUR_12_CNT, DNA_HOUR_13_CNT, DNA_HOUR_14_CNT, DNA_HOUR_15_CNT, DNA_HOUR_16_CNT, DNA_HOUR_17_CNT, DNA_HOUR_18_CNT, DNA_HOUR_19_CNT, DNA_HOUR_20_CNT, DNA_HOUR_21_CNT, DNA_HOUR_22_CNT, DNA_HOUR_23_CNT]
Index: []

[0 rows x 63 columns]

In [33]:
list(s1.columns)

['DATA_MONTH',
 'MINING_DW_SUBSCR_NO',
 'AGE',
 'PTY_CBU_PO_CNT',
 'DORMANT_MONTH_CNT_MKT',
 'TENURE_SCV',
 'Groups',
 'VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'voice_monthly_sum',
 'VOICE_HOUR_MON_TIME',
 'VOICE_HOUR_TUE_TIME',
 'VOICE_HOUR_WED_TIME',
 'VOICE_HOUR_THU_TIME',
 'VOICE_HOUR_FRI_TIME',
 'VOICE_HOUR_SAT_TIME',
 'VOICE_HOUR_SUN_TIME',
 'DNA_Monday',
 'DNA_Tuesday',
 'DNA_Wednesday',
 'DNA_Thursday',
 'DNA_Friday',
 'DNA_Saturday',
 'DNA_Sunday',
 'DNA_HOUR_0_CNT',
 'DNA_HOUR_1_CNT',
 'DNA_HOUR_2_CNT',
 'DNA_HOUR_3_CNT',
 'DNA_HOUR_4_CNT',
 'DNA_HOUR_5_CNT',
 'DNA_HOUR_6_CNT',
 'DNA_HOUR_7_CNT',
 'DNA_HOUR_8_CNT',
 'DNA_HOUR_9_CNT',
 'DNA_HOUR_10_CNT',
 'DNA_HOUR_11_CNT',
 'DNA_HOUR_12_CNT',
 'DNA_HOUR_13_CNT',
 'DNA_HOUR_14_CNT',
 'DNA_HOUR_15_CNT',
 'DNA_HOUR_16_CNT',
 'DNA_HOUR_17_CNT',
 'DNA_HOUR_18_CNT',
 'DNA_HOUR_19_CNT',
 'DNA_HOUR_20_CNT',
 'DNA_HOUR_21_CNT',
 'DNA_HOUR_22_CNT',
 'DNA_HOUR_23_CNT',
 'dna_monthly_sum']

In [33]:
list(s1.columns)

['DATA_MONTH',
 'MINING_DW_SUBSCR_NO',
 'AGE',
 'PTY_CBU_PO_CNT',
 'DORMANT_MONTH_CNT_MKT',
 'TENURE_SCV',
 'Groups',
 'VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'voice_monthly_sum',
 'VOICE_HOUR_MON_TIME',
 'VOICE_HOUR_TUE_TIME',
 'VOICE_HOUR_WED_TIME',
 'VOICE_HOUR_THU_TIME',
 'VOICE_HOUR_FRI_TIME',
 'VOICE_HOUR_SAT_TIME',
 'VOICE_HOUR_SUN_TIME',
 'DNA_Monday',
 'DNA_Tuesday',
 'DNA_Wednesday',
 'DNA_Thursday',
 'DNA_Friday',
 'DNA_Saturday',
 'DNA_Sunday',
 'DNA_HOUR_0_CNT',
 'DNA_HOUR_1_CNT',
 'DNA_HOUR_2_CNT',
 'DNA_HOUR_3_CNT',
 'DNA_HOUR_4_CNT',
 'DNA_HOUR_5_CNT',
 'DNA_HOUR_6_CNT',
 'DNA_HOUR_7_CNT',
 'DNA_HOUR_8_CNT',
 'DNA_HOUR_9_CNT',
 'DNA_HOUR_10_CNT',
 'DNA_HOUR_11_CNT',
 'DNA_HOUR_12_CNT',
 'DNA_HOUR_13_CNT',
 'DNA_HOUR_14_CNT',
 'DNA_HOUR_15_CNT',
 'DNA_HOUR_16_CNT',
 'DNA_HOUR_17_CNT',
 'DNA_HOUR_18_CNT',
 'DNA_HOUR_19_CNT',
 'DNA_HOUR_20_CNT',
 'DNA_HOUR_21_CNT',
 'DNA_HOUR_22_CNT',
 'DNA_HOUR_23_CNT',
 'dna_monthly_sum']

In [55]:
max(s1["DNA_HOUR_20_CNT"])

1.0

In [56]:
s1[s1["DNA_HOUR_20_CNT"] > 0.1]

,DATA_MONTH,MINING_DW_SUBSCR_NO,AGE,PTY_CBU_PO_CNT,DORMANT_MONTH_CNT_MKT,TENURE_SCV,Groups,VOICE_HOUR_0_TIME,VOICE_HOUR_1_TIME,VOICE_HOUR_2_TIME,...,DNA_HOUR_15_CNT,DNA_HOUR_16_CNT,DNA_HOUR_17_CNT,DNA_HOUR_18_CNT,DNA_HOUR_19_CNT,DNA_HOUR_20_CNT,DNA_HOUR_21_CNT,DNA_HOUR_22_CNT,DNA_HOUR_23_CNT,dna_monthly_sum
14848,2017/4/1,8137538304,49,1,6,8.7,1,0.000,0.0,0.0,...,0.042,0.054,0.066,0.048,0.048,0.114,0.449,0.120,0.000,0.000
20389,2017/4/1,3135004756,24,1,1,18.5,1,0.111,0.0,0.0,...,0.051,0.095,0.146,0.101,0.063,0.139,0.019,0.000,0.013,0.000
38335,2017/4/1,3126185483,24,1,4,54.4,8,0.000,0.0,0.0,...,0.179,0.088,0.020,0.008,0.009,0.249,0.008,0.015,0.055,0.002
55226,2017/4/1,3128267079,21,1,1,43.3,8,0.000,0.0,0.0,...,0.043,0.005,0.172,0.057,0.032,0.144,0.000,0.117,0.032,0.001
58110,2017/4/1,3131042232,24,1,1,30.7,6,0.000,0.0,0.0,...,0.008,0.008,0.110,0.000,0.039,0.142,0.189,0.102,0.000,0.000
63836,2017/4/1,10000413395,40,1,1,6.0,6,0.011,0.0,0.0,...,0.098,0.009,0.030,0.133,0.082,0.121,0.160,0.027,0.000,0.001
66287,2017/4/1,8134723249,34,1,6,19.6,seldom,0.000,0.0,0.0,...,0.000,0.000,0.000,0.000,0.350,0.200,0.100,0.100,0.000,0.000
77580,2017/4/1,8136433377,39,1,1,12.6,8,0.000,0.0,0.0,...,0.000,0.000,0.000,0.122,0.041,0.122,0.000,0.265,0.102,0.000
78278,2017/4/1,3131505218,62,1,6,29.4,seldom,0.000,0.0,0.0,...,0.667,0.000,0.000,0.000,0.000,0.333,0.000,0.000,0.000,0.000
80911,2017/4/1,8130424231,52,1,2,32.2,seldom,0.000,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000
100138,2017/4/1,8134611285,52,1,1,19.7,seldom,0.000,0.0,0.0,...,0.125,0.000,0.000,0.000,0.125,0.500,0.000,0.000,0.000,0.000
116074,2017/4/1,3125799758,30,1,3,56.5,seldom,0.247,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.143,0.000,0.714,0.000,0.000

In [ ]:
max(s1["DNA_HOUR_0_CNT"])

In [ ]:
s1

In [7]:
# set configure
path = "./CDR_MONTHLY_AGGR/"
path = "./dna_Data/"
# path = "C:/Users/VIPLAB/Downloads/Spark_data/"
filename = "DNA_daily_april"
# filename = "weekday_end_april_div_week"

# path = "./"
# filename = "dm_subscr_mtc_mly_COMPLETED_revise"
relative_filename = path + filename + ".csv"
# relative_filename = path + filename + ".txt"

In [8]:
len(df)

10

In [9]:
list(df.columns)

['MINING_DW_SUBSCR_NO',
 'VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'VOICE_HOUR_MON_TIME',
 'VOICE_HOUR_TUE_TIME',
 'VOICE_HOUR_WED_TIME',
 'VOICE_HOUR_THU_TIME',
 'VOICE_HOUR_FRI_TIME',
 'VOICE_HOUR_SAT_TIME',
 'VOICE_HOUR_SUN_TIME',
 'DNA_Monday',
 'DNA_Tuesday',
 'DNA_Wednesday',
 'DNA_Thursday',
 'DNA_Friday',
 'DNA_Saturday',
 'DNA_Sunday',
 'DNA_HOUR_0_CNT',
 'DNA_HOUR_1_CNT',
 'DNA_HOUR_2_CNT',
 'DNA_HOUR_3_CNT',
 'DNA_HOUR_4_CNT',
 'DNA_HOUR_5_CNT',
 'DNA_HOUR_6_CNT',
 'DNA_HOUR_7_CNT',
 'DNA_HOUR_8_CNT',
 'DNA_HOUR_9_CNT',
 'DNA_HOUR_10_CNT',
 'DNA_HOUR_11_CNT',
 'DNA_HOUR_12_CNT',
 'DNA_HOUR_13_CNT',
 'DNA_HOUR_14_CNT',
 'DNA_HOUR_15_CNT',
 'DNA_HOUR_16_CNT',
 'DNA_HOUR_17_CNT',
 'DNA_HOUR_18_CNT',
 'DNA_HOUR_19_CNT',
 'DNA_HOUR_20_CNT',
 'DNA_HOUR_21_CNT',
 'DNA_HOUR_22_CNT',
 'DNA_HOUR_23_CNT']

In [10]:
df[df["MINING_DW_SUBSCR_NO"] == 10001495017]

Empty DataFrame
Columns: [MINING_DW_SUBSCR_NO, VOICE_HOUR_0_TIME, VOICE_HOUR_1_TIME, VOICE_HOUR_2_TIME, VOICE_HOUR_3_TIME, VOICE_HOUR_4_TIME, VOICE_HOUR_5_TIME, VOICE_HOUR_6_TIME, VOICE_HOUR_7_TIME, VOICE_HOUR_8_TIME, VOICE_HOUR_9_TIME, VOICE_HOUR_10_TIME, VOICE_HOUR_11_TIME, VOICE_HOUR_12_TIME, VOICE_HOUR_13_TIME, VOICE_HOUR_14_TIME, VOICE_HOUR_15_TIME, VOICE_HOUR_16_TIME, VOICE_HOUR_17_TIME, VOICE_HOUR_18_TIME, VOICE_HOUR_19_TIME, VOICE_HOUR_20_TIME, VOICE_HOUR_21_TIME, VOICE_HOUR_22_TIME, VOICE_HOUR_23_TIME, VOICE_HOUR_MON_TIME, VOICE_HOUR_TUE_TIME, VOICE_HOUR_WED_TIME, VOICE_HOUR_THU_TIME, VOICE_HOUR_FRI_TIME, VOICE_HOUR_SAT_TIME, VOICE_HOUR_SUN_TIME, DNA_Monday, DNA_Tuesday, DNA_Wednesday, DNA_Thursday, DNA_Friday, DNA_Saturday, DNA_Sunday, DNA_HOUR_0_CNT, DNA_HOUR_1_CNT, DNA_HOUR_2_CNT, DNA_HOUR_3_CNT, DNA_HOUR_4_CNT, DNA_HOUR_5_CNT, DNA_HOUR_6_CNT, DNA_HOUR_7_CNT, DNA_HOUR_8_CNT, DNA_HOUR_9_CNT, DNA_HOUR_10_CNT, DNA_HOUR_11_CNT, DNA_HOUR_12_CNT, DNA_HOUR_13_CNT, DNA_HOUR_14_CNT, DNA_HOUR_15_CNT, DNA_HOUR_16_CNT, DNA_HOUR_17_CNT, DNA_HOUR_18_CNT, DNA_HOUR_19_CNT, DNA_HOUR_20_CNT, DNA_HOUR_21_CNT, DNA_HOUR_22_CNT, DNA_HOUR_23_CNT]
Index: []

[0 rows x 63 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 63 columns):
MINING_DW_SUBSCR_NO    10 non-null int64
VOICE_HOUR_0_TIME      10 non-null float64
VOICE_HOUR_1_TIME      10 non-null float64
VOICE_HOUR_2_TIME      10 non-null float64
VOICE_HOUR_3_TIME      10 non-null float64
VOICE_HOUR_4_TIME      10 non-null float64
VOICE_HOUR_5_TIME      10 non-null float64
VOICE_HOUR_6_TIME      10 non-null float64
VOICE_HOUR_7_TIME      10 non-null float64
VOICE_HOUR_8_TIME      10 non-null float64
VOICE_HOUR_9_TIME      10 non-null float64
VOICE_HOUR_10_TIME     10 non-null float64
VOICE_HOUR_11_TIME     10 non-null float64
VOICE_HOUR_12_TIME     10 non-null float64
VOICE_HOUR_13_TIME     10 non-null float64
VOICE_HOUR_14_TIME     10 non-null float64
VOICE_HOUR_15_TIME     10 non-null float64
VOICE_HOUR_16_TIME     10 non-null float64
VOICE_HOUR_17_TIME     10 non-null float64
VOICE_HOUR_18_TIME     10 non-null float64
VOICE_HOUR_19_TIME     10 non-null float64
VOICE_HOUR_20_TIME     10 non-null float64
VOICE_HOUR_21_TIME     10 non-null float64
VOICE_HOUR_22_TIME     10 non-null float64
VOICE_HOUR_23_TIME     10 non-null float64
VOICE_HOUR_MON_TIME    10 non-null float64
VOICE_HOUR_TUE_TIME    10 non-null float64
VOICE_HOUR_WED_TIME    10 non-null float64
VOICE_HOUR_THU_TIME    10 non-null float64
VOICE_HOUR_FRI_TIME    10 non-null float64
VOICE_HOUR_SAT_TIME    10 non-null float64
VOICE_HOUR_SUN_TIME    10 non-null float64
DNA_Monday             10 non-null float64
DNA_Tuesday            10 non-null float64
DNA_Wednesday          10 non-null float64
DNA_Thursday           10 non-null float64
DNA_Friday             10 non-null float64
DNA_Saturday           10 non-null float64
DNA_Sunday             10 non-null float64
DNA_HOUR_0_CNT         10 non-null float64
DNA_HOUR_1_CNT         10 non-null float64
DNA_HOUR_2_CNT         10 non-null float64
DNA_HOUR_3_CNT         10 non-null float64
DNA_HOUR_4_CNT         10 non-null float64
DNA_HOUR_5_CNT         10 non-null float64
DNA_HOUR_6_CNT         10 non-null float64
DNA_HOUR_7_CNT         10 non-null float64
DNA_HOUR_8_CNT         10 non-null float64
DNA_HOUR_9_CNT         10 non-null float64
DNA_HOUR_10_CNT        10 non-null float64
DNA_HOUR_11_CNT        10 non-null float64
DNA_HOUR_12_CNT        10 non-null float64
DNA_HOUR_13_CNT        10 non-null float64
DNA_HOUR_14_CNT        10 non-null float64
DNA_HOUR_15_CNT        10 non-null float64
DNA_HOUR_16_CNT        10 non-null float64
DNA_HOUR_17_CNT        10 non-null float64
DNA_HOUR_18_CNT        10 non-null float64
DNA_HOUR_19_CNT        10 non-null float64
DNA_HOUR_20_CNT        10 non-null float64
DNA_HOUR_21_CNT        10 non-null float64
DNA_HOUR_22_CNT        10 non-null float64
DNA_HOUR_23_CNT        10 non-null float64
dtypes: float64(62), int64(1)
memory usage: 5.0 KB

In [12]:
df = df.replace(np.inf, 0)

In [13]:
df = df.fillna(0)

In [14]:
list(df.columns)

['MINING_DW_SUBSCR_NO',
 'VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'VOICE_HOUR_MON_TIME',
 'VOICE_HOUR_TUE_TIME',
 'VOICE_HOUR_WED_TIME',
 'VOICE_HOUR_THU_TIME',
 'VOICE_HOUR_FRI_TIME',
 'VOICE_HOUR_SAT_TIME',
 'VOICE_HOUR_SUN_TIME',
 'DNA_Monday',
 'DNA_Tuesday',
 'DNA_Wednesday',
 'DNA_Thursday',
 'DNA_Friday',
 'DNA_Saturday',
 'DNA_Sunday',
 'DNA_HOUR_0_CNT',
 'DNA_HOUR_1_CNT',
 'DNA_HOUR_2_CNT',
 'DNA_HOUR_3_CNT',
 'DNA_HOUR_4_CNT',
 'DNA_HOUR_5_CNT',
 'DNA_HOUR_6_CNT',
 'DNA_HOUR_7_CNT',
 'DNA_HOUR_8_CNT',
 'DNA_HOUR_9_CNT',
 'DNA_HOUR_10_CNT',
 'DNA_HOUR_11_CNT',
 'DNA_HOUR_12_CNT',
 'DNA_HOUR_13_CNT',
 'DNA_HOUR_14_CNT',
 'DNA_HOUR_15_CNT',
 'DNA_HOUR_16_CNT',
 'DNA_HOUR_17_CNT',
 'DNA_HOUR_18_CNT',
 'DNA_HOUR_19_CNT',
 'DNA_HOUR_20_CNT',
 'DNA_HOUR_21_CNT',
 'DNA_HOUR_22_CNT',
 'DNA_HOUR_23_CNT']

In [15]:
len(list(df.columns))

63

In [16]:
len(df[df["Groups"] == "seldom"])

KeyError: 'Groups'

In [17]:
len(df[df["Groups"] == "None"])

KeyError: 'Groups'

In [ ]:
# clean non numeric data
# iteration avoid memory leak
for col in df.columns[numeric_st_idx:]:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    # let nan == 0
#     print(col)
    df[col] = df[col].fillna(0)
    df[col] = df[col].astype(np.int64)
# df = df.fillna(0)
# # df[df.columns[numeric_st_idx:]] = df[df.columns[numeric_st_idx:]].apply(np.int64)
# for col in df.columns[numeric_st_idx:]:
#     df[col] = df[col].apply(np.int32)

In [ ]:
df.dtypes

In [ ]:
# write to csv and no index
t0 = time()
df.to_csv(out_filename, index=False)
print("time for output csv file: %.2f" % (time()-t0))

In [ ]:
del df

In [ ]:
# read revise csv file and print cost time
t0 = time()
df = pd.read_csv(out_filename, error_bad_lines=False)
print("time for read csv: %.2f" % (time()-t0))

In [ ]:
# show each columns type
df.dtypes