In [1]:
import os.path
import numpy as np
import pandas as pd
from time import time

In [22]:
# set configure
path = "./CDR_MONTHLY_AGGR/"
# path = "./dna_Data/"

filename = "CDR_MO_WEEK_COMPLETED_revise_month_4_aggregate_workday"
path = "C:/Users/VIPLAB/Desktop/XIAO SEAN/"
filename = "DNA_VOICE"
relative_filename = path + filename + ".csv"
out_filename = path + filename + "_revise"+ ".csv"
# after the numeric_st_idx's number will be tranform to int64
numeric_st_idx = 2
# pick the columns of u wants

In [3]:
# read revise csv file and print cost time
t0 = time()
df = pd.read_csv(relative_filename, error_bad_lines=False)
print("time for read csv: %.2f" % (time()-t0))

time for read csv: 20.85

In [4]:
df.head()

,VOICE_HOUR_0_TIME,VOICE_HOUR_1_TIME,VOICE_HOUR_2_TIME,VOICE_HOUR_3_TIME,VOICE_HOUR_4_TIME,VOICE_HOUR_5_TIME,VOICE_HOUR_6_TIME,VOICE_HOUR_7_TIME,VOICE_HOUR_8_TIME,VOICE_HOUR_9_TIME,...,V17,V18,V19,V20,V21,V22,V23,V24,V25,groups
0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.005,0.001,0.030,...,0.028,0.100,0.062,0.035,0.039,0.035,0.037,0.053,0.037,3
1,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.605,0.026,0.000,0.000,0.000,0.000,0.000,15
2,0.0,0.0,0.0,0.0,0.0,0.003,0.007,0.001,0.018,0.111,...,0.033,0.069,0.049,0.101,0.056,0.102,0.094,0.128,0.084,3
3,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.054,0.030,0.004,0.010,0.012,0.048,0.074,0.000,0.036,13
4,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2

In [5]:
list(df.columns)

['VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'groups']

In [6]:
for i in range(1,26):
    df["V" + str(i)].rename("DNA_HOUR_" + str(i-1)), inplace=True)

SyntaxError: invalid syntax (<ipython-input-6-85607af556a9>, line 2)

In [17]:
replace_cols = []

In [18]:
count = 0
for col in df.columns:
    if "V" in col and not "VOICE" in col :
        col = "DNA_HOUR_" + str(count) + "_COUNT"
        count += 1
    replace_cols.append(col)

In [19]:
replace_cols

['VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'DNA_HOUR_0_COUNT',
 'DNA_HOUR_1_COUNT',
 'DNA_HOUR_2_COUNT',
 'DNA_HOUR_3_COUNT',
 'DNA_HOUR_4_COUNT',
 'DNA_HOUR_5_COUNT',
 'DNA_HOUR_6_COUNT',
 'DNA_HOUR_7_COUNT',
 'DNA_HOUR_8_COUNT',
 'DNA_HOUR_9_COUNT',
 'DNA_HOUR_10_COUNT',
 'DNA_HOUR_11_COUNT',
 'DNA_HOUR_12_COUNT',
 'DNA_HOUR_13_COUNT',
 'DNA_HOUR_14_COUNT',
 'DNA_HOUR_15_COUNT',
 'DNA_HOUR_16_COUNT',
 'DNA_HOUR_17_COUNT',
 'DNA_HOUR_18_COUNT',
 'DNA_HOUR_19_COUNT',
 'DNA_HOUR_20_COUNT',
 'DNA_HOUR_21_COUNT',
 'DNA_HOUR_22_COUNT',
 'DNA_HOUR_23_COUNT',
 'groups']

In [20]:
df.columns = replace_cols

In [48]:
# df.rename(columns=lambda x: x.replace("HOUR_", ""), inplace=True)

In [21]:
df.head()

,VOICE_HOUR_0_TIME,VOICE_HOUR_1_TIME,VOICE_HOUR_2_TIME,VOICE_HOUR_3_TIME,VOICE_HOUR_4_TIME,VOICE_HOUR_5_TIME,VOICE_HOUR_6_TIME,VOICE_HOUR_7_TIME,VOICE_HOUR_8_TIME,VOICE_HOUR_9_TIME,...,DNA_HOUR_15_COUNT,DNA_HOUR_16_COUNT,DNA_HOUR_17_COUNT,DNA_HOUR_18_COUNT,DNA_HOUR_19_COUNT,DNA_HOUR_20_COUNT,DNA_HOUR_21_COUNT,DNA_HOUR_22_COUNT,DNA_HOUR_23_COUNT,groups
0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.005,0.001,0.030,...,0.028,0.100,0.062,0.035,0.039,0.035,0.037,0.053,0.037,3
1,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.605,0.026,0.000,0.000,0.000,0.000,0.000,15
2,0.0,0.0,0.0,0.0,0.0,0.003,0.007,0.001,0.018,0.111,...,0.033,0.069,0.049,0.101,0.056,0.102,0.094,0.128,0.084,3
3,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.054,0.030,0.004,0.010,0.012,0.048,0.074,0.000,0.036,13
4,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2

In [39]:
len(df)

4197861

In [23]:
# write to csv and no index
t0 = time()
# aggr_df.to_csv(out_filename + ".csv", index=False, encoding='utf-8')
df.to_csv(out_filename, index=False, encoding='utf-8')
print("time for output csv file: %.2f" % (time()-t0))

time for output csv file: 93.58