In [25]:
import os.path
import numpy as np
import pandas as pd
from time import time

In [26]:
def save_dataframe(df, out_filename):
   # write to csv and no index
    t0 = time()
    df.to_csv(out_filename + ".csv", index=False, encoding='utf-8')
#     df.to_csv(out_filename + ".csv", encoding='utf-8')
    print("time for output csv file: %.2f" % (time()-t0))

In [27]:
# set configure
path = "./CDR_FINAL/"
filename = "non_normalize_48_cols"
# path = "./"
# filename = "dm_subscr_mtc_mly_COMPLETED_revise"
out_path = path
relative_filename = path + filename + ".csv"
# relative_filename = path + filename + ".txt"
# wants_cols = ['DATA_MONTH', 'MINING_DW_SUBSCR_NO', 'AGE', "MO_TTL_DURATION","MO_ONNET_DUR","MO_OFFNET_DUR","PSTN_DUR","MO_TTL_COUNT","MO_ONNET_CNT","MO_OFFNET_CNT","PSTN_CNT","MT_TTL_DURATION","MT_ONNET_DUR","MT_OFFNET_DUR","MT_PSTN_DUR","MT_TTL_COUNT","MT_ONNET_CNT","MT_OFFNET_CNT","MT_PSTN_CNT","MOC_FET_DUR","MOC_TWM_DUR","MOC_CHM_DUR","MOC_OTH_DUR","MOC_PSTN_DUR","MOST_MO_DUR","MTC_FET_DUR","MTC_TWM_DUR","MTC_CHM_DUR","MTC_PSTN_DUR","MOST_MT_DUR"]

In [20]:
wants_cols =['MINING_DW_SUBSCR_NO',
 'VOICE_HOUR_0_TIME',
 'VOICE_HOUR_1_TIME',
 'VOICE_HOUR_2_TIME',
 'VOICE_HOUR_3_TIME',
 'VOICE_HOUR_4_TIME',
 'VOICE_HOUR_5_TIME',
 'VOICE_HOUR_6_TIME',
 'VOICE_HOUR_7_TIME',
 'VOICE_HOUR_8_TIME',
 'VOICE_HOUR_9_TIME',
 'VOICE_HOUR_10_TIME',
 'VOICE_HOUR_11_TIME',
 'VOICE_HOUR_12_TIME',
 'VOICE_HOUR_13_TIME',
 'VOICE_HOUR_14_TIME',
 'VOICE_HOUR_15_TIME',
 'VOICE_HOUR_16_TIME',
 'VOICE_HOUR_17_TIME',
 'VOICE_HOUR_18_TIME',
 'VOICE_HOUR_19_TIME',
 'VOICE_HOUR_20_TIME',
 'VOICE_HOUR_21_TIME',
 'VOICE_HOUR_22_TIME',
 'VOICE_HOUR_23_TIME',
 'VOICE_HOUR_MON_TIME',
 'VOICE_HOUR_TUE_TIME',
 'VOICE_HOUR_WED_TIME',
 'VOICE_HOUR_THU_TIME',
 'VOICE_HOUR_FRI_TIME',
 'VOICE_HOUR_SAT_TIME',
 'VOICE_HOUR_SUN_TIME',
 'DNA_Monday',
 'DNA_Tuesday',
 'DNA_Wednesday',
 'DNA_Thursday',
 'DNA_Friday',
 'DNA_Saturday',
 'DNA_Sunday',
 'DNA_HOUR_0_CNT',
 'DNA_HOUR_1_CNT',
 'DNA_HOUR_2_CNT',
 'DNA_HOUR_3_CNT',
 'DNA_HOUR_4_CNT',
 'DNA_HOUR_5_CNT',
 'DNA_HOUR_6_CNT',
 'DNA_HOUR_7_CNT',
 'DNA_HOUR_8_CNT',
 'DNA_HOUR_9_CNT',
 'DNA_HOUR_10_CNT',
 'DNA_HOUR_11_CNT',
 'DNA_HOUR_12_CNT',
 'DNA_HOUR_13_CNT',
 'DNA_HOUR_14_CNT',
 'DNA_HOUR_15_CNT',
 'DNA_HOUR_16_CNT',
 'DNA_HOUR_17_CNT',
 'DNA_HOUR_18_CNT',
 'DNA_HOUR_19_CNT',
 'DNA_HOUR_20_CNT',
 'DNA_HOUR_21_CNT',
 'DNA_HOUR_22_CNT',
 'DNA_HOUR_23_CNT']

In [28]:
wants_cols =['MINING_DW_SUBSCR_NO',
 'DNA_HOUR_0_CNT',
 'DNA_HOUR_1_CNT',
 'DNA_HOUR_2_CNT',
 'DNA_HOUR_3_CNT',
 'DNA_HOUR_4_CNT',
 'DNA_HOUR_5_CNT',
 'DNA_HOUR_6_CNT',
 'DNA_HOUR_7_CNT',
 'DNA_HOUR_8_CNT',
 'DNA_HOUR_9_CNT',
 'DNA_HOUR_10_CNT',
 'DNA_HOUR_11_CNT',
 'DNA_HOUR_12_CNT',
 'DNA_HOUR_13_CNT',
 'DNA_HOUR_14_CNT',
 'DNA_HOUR_15_CNT',
 'DNA_HOUR_16_CNT',
 'DNA_HOUR_17_CNT',
 'DNA_HOUR_18_CNT',
 'DNA_HOUR_19_CNT',
 'DNA_HOUR_20_CNT',
 'DNA_HOUR_21_CNT',
 'DNA_HOUR_22_CNT',
 'DNA_HOUR_23_CNT']

In [19]:
wants_cols =['MINING_DW_SUBSCR_NO',
    'VOICE_HOUR_MON_TIME',
 'VOICE_HOUR_TUE_TIME',
 'VOICE_HOUR_WED_TIME',
 'VOICE_HOUR_THU_TIME',
 'VOICE_HOUR_FRI_TIME',
 'VOICE_HOUR_SAT_TIME',
 'VOICE_HOUR_SUN_TIME',
 'DNA_Monday',
 'DNA_Tuesday',
 'DNA_Wednesday',
 'DNA_Thursday',
 'DNA_Friday',
 'DNA_Saturday',
 'DNA_Sunday']

In [30]:
# read csv file and print cost time
t0 = time()
# df = pd.read_csv(relative_filename, usecols = wants_cols, error_bad_lines=False, nrows = 100000)
# df = pd.read_csv(relative_filename, error_bad_lines=False, nrows = 10)
df = pd.read_csv(relative_filename, error_bad_lines=False, usecols = wants_cols)
# df = pd.read_csv(relative_filename, error_bad_lines=False)
print("time for read csv: %.2f" % (time()-t0))

time for read csv: 18.00

In [31]:
df.head()

,MINING_DW_SUBSCR_NO,DNA_HOUR_0_CNT,DNA_HOUR_1_CNT,DNA_HOUR_2_CNT,DNA_HOUR_3_CNT,DNA_HOUR_4_CNT,DNA_HOUR_5_CNT,DNA_HOUR_6_CNT,DNA_HOUR_7_CNT,DNA_HOUR_8_CNT,...,DNA_HOUR_14_CNT,DNA_HOUR_15_CNT,DNA_HOUR_16_CNT,DNA_HOUR_17_CNT,DNA_HOUR_18_CNT,DNA_HOUR_19_CNT,DNA_HOUR_20_CNT,DNA_HOUR_21_CNT,DNA_HOUR_22_CNT,DNA_HOUR_23_CNT
0,10000000005,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,10000000006,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,10000000008,0.031218,0.022446,0.011868,0.011352,0.009288,0.005676,0.010062,0.016254,0.069401,...,0.043602,0.058308,0.047730,0.059856,0.054180,0.040506,0.049278,0.047472,0.033540,0.037410
3,10000000013,0.021439,0.000849,0.004882,0.019104,0.000000,0.005519,0.047124,0.039058,0.055615,...,0.016345,0.016982,0.018467,0.018467,0.031840,0.048185,0.305668,0.139673,0.023986,0.042029
4,10000000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031903,0.078108,...,0.066007,0.091309,0.037404,0.124312,0.141914,0.009901,0.068207,0.052805,0.014301,0.007701

In [32]:
save_dataframe(df, out_path +  "dna_hours_divide")
# save_dataframe(df, out_path +  "day_divide")

time for output csv file: 70.96

In [33]:
def process_csv_kmean_result(filename, concat_df):
    # read revise csv file and print cost time
    kmean_df = pd.read_csv(filename, error_bad_lines=False, usecols = ["MINING_DW_SUBSCR_NO", "Groups"])
    concat_df = pd.merge(kmean_df, concat_df, on='MINING_DW_SUBSCR_NO', how='left')
    return concat_df

In [36]:
# TAG K MEAN RESULT
# TAG K MEAN RESULT
path = "./"
filename = "DNA_KMEANS_RESULT_ID_NEW.csv"
KMEANS_RESULT_ID_FILE = path + filename
df = process_csv_kmean_result(KMEANS_RESULT_ID_FILE, df)

In [39]:
split_list = ["1", "2", "3", "4", "5", "6", "7", "8", "seldom", "None" ]
for kid in split_list:
    temp_df = df[df["Groups"] == kid]
    temp_df = temp_df.drop("Groups", 1)
    
    save_dataframe(temp_df, out_path + "dna_hours_divide_with_kid_" + kid)

time for output csv file: 12.12
time for output csv file: 5.91
time for output csv file: 3.33
time for output csv file: 3.72
time for output csv file: 3.64
time for output csv file: 4.83
time for output csv file: 5.78
time for output csv file: 16.38
time for output csv file: 7.32
time for output csv file: 6.32

In [5]:
df.head()

,MINING_DW_SUBSCR_NO,VOICE_MT_HOUR_0_CNT,VOICE_MT_HOUR_1_CNT,VOICE_MT_HOUR_2_CNT,VOICE_MT_HOUR_3_CNT,VOICE_MT_HOUR_4_CNT,VOICE_MT_HOUR_5_CNT,VOICE_MT_HOUR_6_CNT,VOICE_MT_HOUR_7_CNT,VOICE_MT_HOUR_8_CNT,...,VOICE_MT_HOUR_14_TIME,VOICE_MT_HOUR_15_TIME,VOICE_MT_HOUR_16_TIME,VOICE_MT_HOUR_17_TIME,VOICE_MT_HOUR_18_TIME,VOICE_MT_HOUR_19_TIME,VOICE_MT_HOUR_20_TIME,VOICE_MT_HOUR_21_TIME,VOICE_MT_HOUR_22_TIME,VOICE_MT_HOUR_23_TIME
0,1171,0,0,0,0,0,0,0,1,0,...,169,0,585,0,15,399,0,0,0,0
1,1179,0,0,0,0,0,0,0,3,9,...,953,788,2958,1496,802,1601,408,1128,479,0
2,1181,0,0,0,0,0,0,0,1,1,...,0,58,197,300,113,124,52,0,22,0
3,11121,3,1,2,0,0,0,0,0,2,...,271,96,81,208,142,46,107,0,0,107
4,11131,0,0,0,0,0,2,4,6,4,...,68,200,299,73,281,299,17,14,0,0

In [6]:
list(df.columns)

['MINING_DW_SUBSCR_NO',
 'VOICE_MT_HOUR_0_CNT',
 'VOICE_MT_HOUR_1_CNT',
 'VOICE_MT_HOUR_2_CNT',
 'VOICE_MT_HOUR_3_CNT',
 'VOICE_MT_HOUR_4_CNT',
 'VOICE_MT_HOUR_5_CNT',
 'VOICE_MT_HOUR_6_CNT',
 'VOICE_MT_HOUR_7_CNT',
 'VOICE_MT_HOUR_8_CNT',
 'VOICE_MT_HOUR_9_CNT',
 'VOICE_MT_HOUR_10_CNT',
 'VOICE_MT_HOUR_11_CNT',
 'VOICE_MT_HOUR_12_CNT',
 'VOICE_MT_HOUR_13_CNT',
 'VOICE_MT_HOUR_14_CNT',
 'VOICE_MT_HOUR_15_CNT',
 'VOICE_MT_HOUR_16_CNT',
 'VOICE_MT_HOUR_17_CNT',
 'VOICE_MT_HOUR_18_CNT',
 'VOICE_MT_HOUR_19_CNT',
 'VOICE_MT_HOUR_20_CNT',
 'VOICE_MT_HOUR_21_CNT',
 'VOICE_MT_HOUR_22_CNT',
 'VOICE_MT_HOUR_23_CNT',
 'VOICE_MT_HOUR_0_TIME',
 'VOICE_MT_HOUR_1_TIME',
 'VOICE_MT_HOUR_2_TIME',
 'VOICE_MT_HOUR_3_TIME',
 'VOICE_MT_HOUR_4_TIME',
 'VOICE_MT_HOUR_5_TIME',
 'VOICE_MT_HOUR_6_TIME',
 'VOICE_MT_HOUR_7_TIME',
 'VOICE_MT_HOUR_8_TIME',
 'VOICE_MT_HOUR_9_TIME',
 'VOICE_MT_HOUR_10_TIME',
 'VOICE_MT_HOUR_11_TIME',
 'VOICE_MT_HOUR_12_TIME',
 'VOICE_MT_HOUR_13_TIME',
 'VOICE_MT_HOUR_14_TIME',
 'VOICE_MT_HOUR_15_TIME',
 'VOICE_MT_HOUR_16_TIME',
 'VOICE_MT_HOUR_17_TIME',
 'VOICE_MT_HOUR_18_TIME',
 'VOICE_MT_HOUR_19_TIME',
 'VOICE_MT_HOUR_20_TIME',
 'VOICE_MT_HOUR_21_TIME',
 'VOICE_MT_HOUR_22_TIME',
 'VOICE_MT_HOUR_23_TIME']

In [33]:
df[df["MINING_DW_SUBSCR_NO"] == 10001495017]

,MINING_DW_SUBSCR_NO,VOICE_MO_HOUR_SUN_CNT,VOICE_MO_HOUR_MON_CNT,VOICE_MO_HOUR_TUE_CNT,VOICE_MO_HOUR_WED_CNT,VOICE_MO_HOUR_THU_CNT,VOICE_MO_HOUR_FRI_CNT,VOICE_MO_HOUR_SAT_CNT,VOICE_MO_HOUR_SUN_TIME,VOICE_MO_HOUR_MON_TIME,...,VOICE_MT_FRI_TIME,VOICE_MT_SAT_TIME,VOICE_MT_workday_cnt,VOICE_MT_workday_cnt_avg,VOICE_MT_workday_time,VOICE_MT_workday_time_avg,VOICE_MT_holiday_cnt,VOICE_MT_holiday_cnt_avg,VOICE_MT_holiday_time,VOICE_MT_holiday_time_avg
282,10001495017,2,8,0,2,2,3,0,631,404,...,232,212,37,7.4,1301,260.2,8,4.0,1092,546.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Columns: 169 entries, MINING_DW_SUBSCR_NO to VOICE_MT_holiday_time_avg
dtypes: float64(8), int64(161)
memory usage: 13.3 KB

In [58]:
df = df.replace(np.inf, 0)

In [51]:
df = df.fillna(0)

In [11]:
list(df.columns)

['MINING_DW_SUBSCR_NO',
 'VOICE_MO_HOUR_0_CNT',
 'VOICE_MO_HOUR_1_CNT',
 'VOICE_MO_HOUR_2_CNT',
 'VOICE_MO_HOUR_3_CNT',
 'VOICE_MO_HOUR_4_CNT',
 'VOICE_MO_HOUR_5_CNT',
 'VOICE_MO_HOUR_6_CNT',
 'VOICE_MO_HOUR_7_CNT',
 'VOICE_MO_HOUR_8_CNT',
 'VOICE_MO_HOUR_9_CNT',
 'VOICE_MO_HOUR_10_CNT',
 'VOICE_MO_HOUR_11_CNT',
 'VOICE_MO_HOUR_12_CNT',
 'VOICE_MO_HOUR_13_CNT',
 'VOICE_MO_HOUR_14_CNT',
 'VOICE_MO_HOUR_15_CNT',
 'VOICE_MO_HOUR_16_CNT',
 'VOICE_MO_HOUR_17_CNT',
 'VOICE_MO_HOUR_18_CNT',
 'VOICE_MO_HOUR_19_CNT',
 'VOICE_MO_HOUR_20_CNT',
 'VOICE_MO_HOUR_21_CNT',
 'VOICE_MO_HOUR_22_CNT',
 'VOICE_MO_HOUR_23_CNT',
 'VOICE_MO_HOUR_0_TIME',
 'VOICE_MO_HOUR_1_TIME',
 'VOICE_MO_HOUR_2_TIME',
 'VOICE_MO_HOUR_3_TIME',
 'VOICE_MO_HOUR_4_TIME',
 'VOICE_MO_HOUR_5_TIME',
 'VOICE_MO_HOUR_6_TIME',
 'VOICE_MO_HOUR_7_TIME',
 'VOICE_MO_HOUR_8_TIME',
 'VOICE_MO_HOUR_9_TIME',
 'VOICE_MO_HOUR_10_TIME',
 'VOICE_MO_HOUR_11_TIME',
 'VOICE_MO_HOUR_12_TIME',
 'VOICE_MO_HOUR_13_TIME',
 'VOICE_MO_HOUR_14_TIME',
 'VOICE_MO_HOUR_15_TIME',
 'VOICE_MO_HOUR_16_TIME',
 'VOICE_MO_HOUR_17_TIME',
 'VOICE_MO_HOUR_18_TIME',
 'VOICE_MO_HOUR_19_TIME',
 'VOICE_MO_HOUR_20_TIME',
 'VOICE_MO_HOUR_21_TIME',
 'VOICE_MO_HOUR_22_TIME',
 'VOICE_MO_HOUR_23_TIME',
 'VOICE_MT_HOUR_0_CNT',
 'VOICE_MT_HOUR_1_CNT',
 'VOICE_MT_HOUR_2_CNT',
 'VOICE_MT_HOUR_3_CNT',
 'VOICE_MT_HOUR_4_CNT',
 'VOICE_MT_HOUR_5_CNT',
 'VOICE_MT_HOUR_6_CNT',
 'VOICE_MT_HOUR_7_CNT',
 'VOICE_MT_HOUR_8_CNT',
 'VOICE_MT_HOUR_9_CNT',
 'VOICE_MT_HOUR_10_CNT',
 'VOICE_MT_HOUR_11_CNT',
 'VOICE_MT_HOUR_12_CNT',
 'VOICE_MT_HOUR_13_CNT',
 'VOICE_MT_HOUR_14_CNT',
 'VOICE_MT_HOUR_15_CNT',
 'VOICE_MT_HOUR_16_CNT',
 'VOICE_MT_HOUR_17_CNT',
 'VOICE_MT_HOUR_18_CNT',
 'VOICE_MT_HOUR_19_CNT',
 'VOICE_MT_HOUR_20_CNT',
 'VOICE_MT_HOUR_21_CNT',
 'VOICE_MT_HOUR_22_CNT',
 'VOICE_MT_HOUR_23_CNT',
 'VOICE_MT_HOUR_0_TIME',
 'VOICE_MT_HOUR_1_TIME',
 'VOICE_MT_HOUR_2_TIME',
 'VOICE_MT_HOUR_3_TIME',
 'VOICE_MT_HOUR_4_TIME',
 'VOICE_MT_HOUR_5_TIME',
 'VOICE_MT_HOUR_6_TIME',
 'VOICE_MT_HOUR_7_TIME',
 'VOICE_MT_HOUR_8_TIME',
 'VOICE_MT_HOUR_9_TIME',
 'VOICE_MT_HOUR_10_TIME',
 'VOICE_MT_HOUR_11_TIME',
 'VOICE_MT_HOUR_12_TIME',
 'VOICE_MT_HOUR_13_TIME',
 'VOICE_MT_HOUR_14_TIME',
 'VOICE_MT_HOUR_15_TIME',
 'VOICE_MT_HOUR_16_TIME',
 'VOICE_MT_HOUR_17_TIME',
 'VOICE_MT_HOUR_18_TIME',
 'VOICE_MT_HOUR_19_TIME',
 'VOICE_MT_HOUR_20_TIME',
 'VOICE_MT_HOUR_21_TIME',
 'VOICE_MT_HOUR_22_TIME',
 'VOICE_MT_HOUR_23_TIME',
 'MTC_CNT',
 'MTC_DUR',
 'MTC_FET_CNT',
 'MTC_FET_DUR',
 'MTC_TWM_CNT',
 'MTC_TWM_DUR',
 'MTC_CHM_CNT',
 'MTC_CHM_DUR',
 'MTC_APT_CNT',
 'MTC_APT_DUR',
 'MTC_TSC_CNT',
 'MTC_TSC_DUR',
 'MTC_PSTN_CNT',
 'MTC_PSTN_DUR',
 'MOC_CNT',
 'MOC_DUR',
 'MOC_FET_CNT',
 'MOC_FET_DUR',
 'MOC_TWM_CNT',
 'MOC_TWM_DUR',
 'MOC_CHM_CNT',
 'MOC_CHM_DUR',
 'MOC_APT_CNT',
 'MOC_APT_DUR',
 'MOC_TSC_CNT',
 'MOC_TSC_DUR',
 'MOC_PSTN_CNT',
 'MOC_PSTN_DUR',
 'VOICE_MO_HOUR_SUN_CNT',
 'VOICE_MO_HOUR_MON_CNT',
 'VOICE_MO_HOUR_TUE_CNT',
 'VOICE_MO_HOUR_WED_CNT',
 'VOICE_MO_HOUR_THU_CNT',
 'VOICE_MO_HOUR_FRI_CNT',
 'VOICE_MO_HOUR_SAT_CNT',
 'VOICE_MO_HOUR_SUN_TIME',
 'VOICE_MO_HOUR_MON_TIME',
 'VOICE_MO_HOUR_TUE_TIME',
 'VOICE_MO_HOUR_WED_TIME',
 'VOICE_MO_HOUR_THU_TIME',
 'VOICE_MO_HOUR_FRI_TIME',
 'VOICE_MO_HOUR_SAT_TIME',
 'VOICE_MO_workday_cnt',
 'VOICE_MO_workday_cnt_avg',
 'VOICE_MO_workday_time',
 'VOICE_MO_workday_time_avg',
 'VOICE_MO_holiday_cnt',
 'VOICE_MO_holiday_cnt_avg',
 'VOICE_MO_holiday_time',
 'VOICE_MO_holiday_time_avg',
 'VOICE_MT_SUN_CNT',
 'VOICE_MT_MON_CNT',
 'VOICE_MT_TUE_CNT',
 'VOICE_MT_WED_CNT',
 'VOICE_MT_THU_CNT',
 'VOICE_MT_FRI_CNT',
 'VOICE_MT_SAT_CNT',
 'VOICE_MT_SUN_TIME',
 'VOICE_MT_MON_TIME',
 'VOICE_MT_TUE_TIME',
 'VOICE_MT_WED_TIME',
 'VOICE_MT_THU_TIME',
 'VOICE_MT_FRI_TIME',
 'VOICE_MT_SAT_TIME',
 'VOICE_MT_workday_cnt',
 'VOICE_MT_workday_cnt_avg',
 'VOICE_MT_workday_time',
 'VOICE_MT_workday_time_avg',
 'VOICE_MT_holiday_cnt',
 'VOICE_MT_holiday_cnt_avg',
 'VOICE_MT_holiday_time',
 'VOICE_MT_holiday_time_avg']

In [8]:
len(list(df.columns))

12

In [7]:
len(df[df["Groups"] == "seldom"])

1

In [23]:
len(df[df["Groups"] == "None"])

531990

In [21]:
# clean non numeric data
# iteration avoid memory leak
for col in df.columns[numeric_st_idx:]:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    # let nan == 0
#     print(col)
    df[col] = df[col].fillna(0)
    df[col] = df[col].astype(np.int64)
# df = df.fillna(0)
# # df[df.columns[numeric_st_idx:]] = df[df.columns[numeric_st_idx:]].apply(np.int64)
# for col in df.columns[numeric_st_idx:]:
#     df[col] = df[col].apply(np.int32)

In [35]:
df.dtypes

MINING_DW_SUBSCR_NO         int64
hour(7~11)_time           float64
hour(12~13)_time          float64
hour(14~19)_time          float64
hour(20~3)_time           float64
hour(4~6)_time            float64
VOICE_workday_time_avg    float64
VOICE_holiday_time_avg    float64
FET_time                  float64
FET_cnt                   float64
TWM_time                  float64
TWM_cnt                   float64
CHM_time                  float64
CHM_cnt                   float64
APT_time                  float64
APT_cnt                   float64
TSC_time                  float64
TSC_cnt                   float64
PSTN_time                 float64
PSTN_cnt                  float64
MOC_time_avg              float64
MTC_time_avg              float64
MO/MT_CNT                 float64
dtype: object

In [23]:
# write to csv and no index
t0 = time()
df.to_csv(out_filename, index=False)
print("time for output csv file: %.2f" % (time()-t0))

time for output csv file: 143.23

In [9]:
del df

In [ ]:
# read revise csv file and print cost time
t0 = time()
df = pd.read_csv(out_filename, error_bad_lines=False)
print("time for read csv: %.2f" % (time()-t0))

In [ ]:
# show each columns type
df.dtypes