# Read & Clear Data

In [1]:
import os.path
import numpy as np
import pandas as pd
from time import time
from sklearn.model_selection import train_test_split

In [2]:
# set configure
# path = "./CDR_MONTHLY_AGGR/"
# path = "D:/0625_fet_analyze/CDR_FINAL/"
# path = "C:/Users/VIPLAB/Downloads/Spark_data/"
path = "./marketing_analyze/"
filename = "april_marketing_anylze_numeric_and_bool_max_min"
# path = "./"
# filename = "dm_subscr_mtc_mly_COMPLETED_revise"
relative_filename = path + filename + ".csv"
# relative_filename = path + filename + ".txt"

In [3]:
t0 = time()
df = pd.read_csv(relative_filename, error_bad_lines=False)
print("time for read csv: %.2f" % (time()-t0))

time for read csv: 119.40

In [4]:
df.head()

,RENEW_IND,GA_IND,CHURN_IND,SUSPEND_IND,P6M_AVG_NET_INV_AMT,TENURE_SCV,CHURN_INDEX,FETNET_IND,DORMANT_MONTH_CNT_MKT,HAPPYGO_IND,...,EVER_PSTN_MONTH_APPLY_CANCEL_FLAG,VIP_REDEEM_IND,VIP_MSISDN_CHG_IND,PAY_PENALTY_FLAG,DATA_RATING_USAGE_MB,SELFCARE_IND,RETAIL_STORE_CHURN_FLAG,RETAIL_STORE_CHURN_DEPUTY_FALG,SPAUTH_IND,Groups
0,0.0,0.0,0.0,0.0,0.045928,0.784494,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000829,1.0,0.0,0.0,0.0,seldom
1,0.0,0.0,0.0,0.0,0.039339,0.784494,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000672,0.0,0.0,0.0,0.0,2
2,0.0,0.0,0.0,0.0,0.053191,0.784494,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.000607,1.0,0.0,0.0,0.0,3
3,0.0,0.0,0.0,0.0,0.048370,0.784494,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.000596,1.0,0.0,0.0,0.0,seldom
4,0.0,0.0,0.0,0.0,0.040959,0.784494,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000458,1.0,0.0,0.0,0.0,2

In [5]:
# delete questionable rows
df_clear = df.drop(df[df['Groups'] == 'kid'].index)
df_clear = df_clear.drop(df_clear[df_clear['Groups'] == 'single'].index)

In [6]:
# verify deletion
df_clear.groupby('Groups').count()

,RENEW_IND,GA_IND,CHURN_IND,SUSPEND_IND,P6M_AVG_NET_INV_AMT,TENURE_SCV,CHURN_INDEX,FETNET_IND,DORMANT_MONTH_CNT_MKT,HAPPYGO_IND,...,EVER_PSTN_FEATURE_FLAG,EVER_PSTN_MONTH_APPLY_CANCEL_FLAG,VIP_REDEEM_IND,VIP_MSISDN_CHG_IND,PAY_PENALTY_FLAG,DATA_RATING_USAGE_MB,SELFCARE_IND,RETAIL_STORE_CHURN_FLAG,RETAIL_STORE_CHURN_DEPUTY_FALG,SPAUTH_IND
Groups,,,,,,,,,,,,,,,,,,,,,
1,407593,407593,407593,407593,407593,407593,407593,407593,407593,407593,...,407593,407593,407593,407593,407593,407593,407593,407593,407593,407593
2,184643,184643,184643,184643,184643,184643,184643,184643,184643,184643,...,184643,184643,184643,184643,184643,184643,184643,184643,184643,184643
3,105809,105809,105809,105809,105809,105809,105809,105809,105809,105809,...,105809,105809,105809,105809,105809,105809,105809,105809,105809,105809
4,116958,116958,116958,116958,116958,116958,116958,116958,116958,116958,...,116958,116958,116958,116958,116958,116958,116958,116958,116958,116958
5,110473,110473,110473,110473,110473,110473,110473,110473,110473,110473,...,110473,110473,110473,110473,110473,110473,110473,110473,110473,110473
6,146045,146045,146045,146045,146045,146045,146045,146045,146045,146045,...,146045,146045,146045,146045,146045,146045,146045,146045,146045,146045
7,164149,164149,164149,164149,164149,164149,164149,164149,164149,164149,...,164149,164149,164149,164149,164149,164149,164149,164149,164149,164149
8,490164,490164,490164,490164,490164,490164,490164,490164,490164,490164,...,490164,490164,490164,490164,490164,490164,490164,490164,490164,490164
None,531990,531990,531990,531990,531990,531990,531990,531990,531990,531990,...,531990,531990,531990,531990,531990,531990,531990,531990,531990,531990
seldom,338963,338963,338963,338963,338963,338963,338963,338963,338963,338963,...,338963,338963,338963,338963,338963,338963,338963,338963,338963,338963

In [7]:
# train, test = train_test_split(df, test_size = 0.4, random_state = 200)
train, test = train_test_split(df_clear, test_size = 0.4, random_state = 200)

In [8]:
train_x, train_y = train.iloc[:, 0:-1], train.iloc[:, -1]

In [9]:
test_x, test_y = test.iloc[:, 0:-1], test.iloc[:, -1]

In [10]:
len(train_x)

1558072

In [11]:
len(test_x)

1038715

In [12]:
train.groupby('Groups').count()

,RENEW_IND,GA_IND,CHURN_IND,SUSPEND_IND,P6M_AVG_NET_INV_AMT,TENURE_SCV,CHURN_INDEX,FETNET_IND,DORMANT_MONTH_CNT_MKT,HAPPYGO_IND,...,EVER_PSTN_FEATURE_FLAG,EVER_PSTN_MONTH_APPLY_CANCEL_FLAG,VIP_REDEEM_IND,VIP_MSISDN_CHG_IND,PAY_PENALTY_FLAG,DATA_RATING_USAGE_MB,SELFCARE_IND,RETAIL_STORE_CHURN_FLAG,RETAIL_STORE_CHURN_DEPUTY_FALG,SPAUTH_IND
Groups,,,,,,,,,,,,,,,,,,,,,
1,244632,244632,244632,244632,244632,244632,244632,244632,244632,244632,...,244632,244632,244632,244632,244632,244632,244632,244632,244632,244632
2,110824,110824,110824,110824,110824,110824,110824,110824,110824,110824,...,110824,110824,110824,110824,110824,110824,110824,110824,110824,110824
3,63509,63509,63509,63509,63509,63509,63509,63509,63509,63509,...,63509,63509,63509,63509,63509,63509,63509,63509,63509,63509
4,70267,70267,70267,70267,70267,70267,70267,70267,70267,70267,...,70267,70267,70267,70267,70267,70267,70267,70267,70267,70267
5,66266,66266,66266,66266,66266,66266,66266,66266,66266,66266,...,66266,66266,66266,66266,66266,66266,66266,66266,66266,66266
6,87730,87730,87730,87730,87730,87730,87730,87730,87730,87730,...,87730,87730,87730,87730,87730,87730,87730,87730,87730,87730
7,98343,98343,98343,98343,98343,98343,98343,98343,98343,98343,...,98343,98343,98343,98343,98343,98343,98343,98343,98343,98343
8,293912,293912,293912,293912,293912,293912,293912,293912,293912,293912,...,293912,293912,293912,293912,293912,293912,293912,293912,293912,293912
None,319288,319288,319288,319288,319288,319288,319288,319288,319288,319288,...,319288,319288,319288,319288,319288,319288,319288,319288,319288,319288
seldom,203301,203301,203301,203301,203301,203301,203301,203301,203301,203301,...,203301,203301,203301,203301,203301,203301,203301,203301,203301,203301

In [13]:
test.groupby('Groups').count()

,RENEW_IND,GA_IND,CHURN_IND,SUSPEND_IND,P6M_AVG_NET_INV_AMT,TENURE_SCV,CHURN_INDEX,FETNET_IND,DORMANT_MONTH_CNT_MKT,HAPPYGO_IND,...,EVER_PSTN_FEATURE_FLAG,EVER_PSTN_MONTH_APPLY_CANCEL_FLAG,VIP_REDEEM_IND,VIP_MSISDN_CHG_IND,PAY_PENALTY_FLAG,DATA_RATING_USAGE_MB,SELFCARE_IND,RETAIL_STORE_CHURN_FLAG,RETAIL_STORE_CHURN_DEPUTY_FALG,SPAUTH_IND
Groups,,,,,,,,,,,,,,,,,,,,,
1,162961,162961,162961,162961,162961,162961,162961,162961,162961,162961,...,162961,162961,162961,162961,162961,162961,162961,162961,162961,162961
2,73819,73819,73819,73819,73819,73819,73819,73819,73819,73819,...,73819,73819,73819,73819,73819,73819,73819,73819,73819,73819
3,42300,42300,42300,42300,42300,42300,42300,42300,42300,42300,...,42300,42300,42300,42300,42300,42300,42300,42300,42300,42300
4,46691,46691,46691,46691,46691,46691,46691,46691,46691,46691,...,46691,46691,46691,46691,46691,46691,46691,46691,46691,46691
5,44207,44207,44207,44207,44207,44207,44207,44207,44207,44207,...,44207,44207,44207,44207,44207,44207,44207,44207,44207,44207
6,58315,58315,58315,58315,58315,58315,58315,58315,58315,58315,...,58315,58315,58315,58315,58315,58315,58315,58315,58315,58315
7,65806,65806,65806,65806,65806,65806,65806,65806,65806,65806,...,65806,65806,65806,65806,65806,65806,65806,65806,65806,65806
8,196252,196252,196252,196252,196252,196252,196252,196252,196252,196252,...,196252,196252,196252,196252,196252,196252,196252,196252,196252,196252
None,212702,212702,212702,212702,212702,212702,212702,212702,212702,212702,...,212702,212702,212702,212702,212702,212702,212702,212702,212702,212702
seldom,135662,135662,135662,135662,135662,135662,135662,135662,135662,135662,...,135662,135662,135662,135662,135662,135662,135662,135662,135662,135662

In [14]:
df_clear.groupby('Groups').count()

,RENEW_IND,GA_IND,CHURN_IND,SUSPEND_IND,P6M_AVG_NET_INV_AMT,TENURE_SCV,CHURN_INDEX,FETNET_IND,DORMANT_MONTH_CNT_MKT,HAPPYGO_IND,...,EVER_PSTN_FEATURE_FLAG,EVER_PSTN_MONTH_APPLY_CANCEL_FLAG,VIP_REDEEM_IND,VIP_MSISDN_CHG_IND,PAY_PENALTY_FLAG,DATA_RATING_USAGE_MB,SELFCARE_IND,RETAIL_STORE_CHURN_FLAG,RETAIL_STORE_CHURN_DEPUTY_FALG,SPAUTH_IND
Groups,,,,,,,,,,,,,,,,,,,,,
1,407593,407593,407593,407593,407593,407593,407593,407593,407593,407593,...,407593,407593,407593,407593,407593,407593,407593,407593,407593,407593
2,184643,184643,184643,184643,184643,184643,184643,184643,184643,184643,...,184643,184643,184643,184643,184643,184643,184643,184643,184643,184643
3,105809,105809,105809,105809,105809,105809,105809,105809,105809,105809,...,105809,105809,105809,105809,105809,105809,105809,105809,105809,105809
4,116958,116958,116958,116958,116958,116958,116958,116958,116958,116958,...,116958,116958,116958,116958,116958,116958,116958,116958,116958,116958
5,110473,110473,110473,110473,110473,110473,110473,110473,110473,110473,...,110473,110473,110473,110473,110473,110473,110473,110473,110473,110473
6,146045,146045,146045,146045,146045,146045,146045,146045,146045,146045,...,146045,146045,146045,146045,146045,146045,146045,146045,146045,146045
7,164149,164149,164149,164149,164149,164149,164149,164149,164149,164149,...,164149,164149,164149,164149,164149,164149,164149,164149,164149,164149
8,490164,490164,490164,490164,490164,490164,490164,490164,490164,490164,...,490164,490164,490164,490164,490164,490164,490164,490164,490164,490164
None,531990,531990,531990,531990,531990,531990,531990,531990,531990,531990,...,531990,531990,531990,531990,531990,531990,531990,531990,531990,531990
seldom,338963,338963,338963,338963,338963,338963,338963,338963,338963,338963,...,338963,338963,338963,338963,338963,338963,338963,338963,338963,338963

In [15]:
del df

# Train SVM

In [16]:
from sklearn import svm

In [ ]:
clf = svm.LinearSVC(max_iter = 300000)

In [ ]:
clf.fit(train_x, train_y)

# Save Model

In [ ]:
from sklearn.externals import joblib

In [ ]:
joblib.dump(clf, 'LinearSVC.pkl')